class HighlightsNames:
    CHANNELS = "highlights_channels"
    CHANNELS_EXPORT = "highlights_channels_export"
    CHANNELS_PREPARE_EXPORT = "highlights_channels_prepare_export"
    VIDEOS = "highlights_videos"
    VIDEOS_EXPORT = "highlights_videos_export"
    VIDEOS_PREPARE_EXPORT = "highlights_videos_prepare_export"
    KEYWORDS = "highlights_keywords"
    KEYWORDS_EXPORT = "highlights_keywords_export"
    KEYWORDS_PREPARE_EXPORT = "highlights_keywords_prepare_export"
