# Generated by Django 3.1.6 on 2021-02-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftux', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftux',
            name='meta_data',
            field=models.JSONField(default=dict),
        ),
    ]
