# Generated by Django 3.1.6 on 2021-02-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_reports', '0002_videocreativedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocreativedata',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
