version: '3'

services:
  pg:
    image: postgres:9.6
    environment:
      POSTGRES_DB: saas
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  api:
    build: .
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    environment:
      SINGLE_DATABASE_API_HOST: localhost
      TEAMCITY_VERSION: ${TEAMCITY_VERSION}
    depends_on:
      - pg