version: '3'

services:
  api:
    environment:
      SINGLE_DATABASE_API_HOST: localhost
      TEAMCITY_VERSION: ${TEAMCITY_VERSION}
    depends_on:
      - pg

  web:
    image: busybox
  sdb:
    image: busybox
  es:
    image: busybox
  cassandra:
    image: busybox
  rabbitmq:
    image: busybox

