TOP_LEVEL_CATEGORIES = [
    "automotive",
    "books & literature",
    "business & finance",
    "careers",
    "education",
    "events & attractions",
    "family & relationships",
    "fine art",
    "food & drink",
    "healthy living",
    "hobbies & interests",
    "home & garden",
    "medical health",
    "movies",
    "music & audio",
    "news & politics",
    "personal finance",
    "pets",
    "pop culture",
    "real estate",
    "religion & spirituality",
    "science",
    "shopping",
    "sports",
    "style & fashion",
    "technology & computing",
    "television",
    "travel",
    "video gaming",
    "comedy",
    "nonprofits & activism",
    "kids content",
    "people & blogs"
]

IAB_TO_YOUTUBE_CATEGORIES_MAPPING = {
    "automotive": "autos & vehicles",
    "education": "education",
    "movies": "film & animation",
    "music & audio": "music",
    "news & politics": "news & politics",
    "pets": "pets & animals",
    "pop culture": "entertainment",
    "sports": "sports",
    "style & fashion": "howto & style",
    "technology & computing": "science and technology",
    "travel": "travel & events",
    "video gaming": "gaming",
    "comedy": "comedy",
    "nonprofits & activism": "nonprofits & activism",
    "kids content": "kids content",
    "people & blogs": "people & blogs"
}

YOUTUBE_TO_IAB_CATEGORIES_MAPPING = {value: key for key, value in IAB_TO_YOUTUBE_CATEGORIES_MAPPING.items()}
