# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-15 13:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelRelation',
            fields=[
                ('channel_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('segment_type', models.CharField(max_length=255)),
                ('category', models.CharField(default='private', max_length=255)),
                ('statistics', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('mini_dash_data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('channels', models.ManyToManyField(blank=True, related_name='segments', to='segment.ChannelRelation')),
            ],
        ),
        migrations.CreateModel(
            name='VideoRelation',
            fields=[
                ('video_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='segment',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='segments', to='segment.VideoRelation'),
        ),
    ]
