# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-17 13:21
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('segment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
