# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-17 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0002_segment_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='segment_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
