# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-17 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0003_auto_20170517_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
