# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-13 07:11
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('segment', '0006_auto_20170612_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('statistics', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('mini_dash_data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('category', models.CharField(choices=[('private', 'private'), ('youtube', 'youtube'), ('iab', 'iab'), ('cas', 'cas'), ('blacklist', 'blacklist')], max_length=255)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SegmentRelatedChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_id', models.CharField(max_length=30)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related', to='segment.SegmentChannel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SegmentRelatedVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_id', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SegmentVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('statistics', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('mini_dash_data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('category', models.CharField(choices=[('youtube', 'youtube'), ('blacklist', 'blacklist'), ('private', 'private'), ('iab', 'iab')], max_length=255)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='segmentrelatedvideo',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related', to='segment.SegmentVideo'),
        ),
        migrations.AlterUniqueTogether(
            name='segmentrelatedvideo',
            unique_together=set([('segment', 'related_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='segmentrelatedchannel',
            unique_together=set([('segment', 'related_id')]),
        ),
    ]
