# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-16 13:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0007_auto_20170614_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segmentchannel',
            name='statistics',
        ),
        migrations.RemoveField(
            model_name='segmentkeyword',
            name='statistics',
        ),
        migrations.RemoveField(
            model_name='segmentvideo',
            name='statistics',
        ),
        migrations.AddField(
            model_name='segmentchannel',
            name='channels',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='segmentchannel',
            name='comments',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='segmentchannel',
            name='dislikes',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='segmentchannel',
            name='engage_rate',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='segmentchannel',
            name='likes',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='segmentchannel',
            name='sentiment',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='segmentchannel',
            name='subscribers',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='segmentchannel',
            name='subscribers_per_channel',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='segmentchannel',
            name='top_three_channels',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='segmentchannel',
            name='video_views',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='segmentchannel',
            name='videos',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='segmentchannel',
            name='views',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='segmentchannel',
            name='views_per_channel',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='segmentvideo',
            name='comments',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='segmentvideo',
            name='dislikes',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='segmentvideo',
            name='engage_rate',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='segmentvideo',
            name='likes',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='segmentvideo',
            name='sentiment',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='segmentvideo',
            name='thirty_days_views',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='segmentvideo',
            name='top_three_videos',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='segmentvideo',
            name='videos',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='segmentvideo',
            name='views',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='segmentvideo',
            name='views_per_video',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
