# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-12-27 16:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0011_segmentkeyword_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentkeyword',
            name='average_cpc',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='segmentkeyword',
            name='average_volume',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='segmentkeyword',
            name='competition',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='segmentkeyword',
            name='top_keywords',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
