# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-01-09 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0012_auto_20171227_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentkeyword',
            name='category',
            field=models.CharField(choices=[('youtube', 'youtube'), ('channel_factory', 'channel_factory'), ('blacklist', 'blacklist'), ('private', 'private')], max_length=255),
        ),
        migrations.AlterField(
            model_name='segmentrelatedchannel',
            name='related_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='segmentrelatedkeyword',
            name='related_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='segmentrelatedvideo',
            name='related_id',
            field=models.CharField(max_length=100),
        ),
    ]
