# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-01-09 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0013_auto_20180109_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentkeyword',
            name='category',
            field=models.CharField(choices=[('youtube', 'youtube'), ('chf', 'chf'), ('blacklist', 'blacklist'), ('private', 'private')], max_length=255),
        ),
    ]
