# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-03-11 23:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0014_auto_20180109_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentchannel',
            name='adw_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='segmentkeyword',
            name='adw_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='segmentvideo',
            name='adw_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
