# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-04-02 15:55
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0015_auto_20180311_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentchannel',
            name='shared_with',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='segmentkeyword',
            name='shared_with',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='segmentvideo',
            name='shared_with',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
