# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-03 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0016_auto_20180402_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segmentchannel',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='segmentkeyword',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='segmentvideo',
            options={'ordering': ['pk']},
        ),
    ]
