# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-27 06:00
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0017_auto_20181003_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersistentSegmentChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('shared_with', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('category', models.CharField(choices=[('blacklist', 'blacklist'), ('whitelist', 'whitelist')], max_length=255)),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersistentSegmentRelatedChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_id', models.CharField(max_length=100)),
                ('title', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('tags', models.TextField(default='')),
                ('thumbnail_image_url', models.TextField(default='')),
                ('statistics', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related', to='segment.PersistentSegmentChannel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersistentSegmentRelatedVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_id', models.CharField(max_length=100)),
                ('title', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('tags', models.TextField(default='')),
                ('thumbnail_image_url', models.TextField(default='')),
                ('statistics', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersistentSegmentVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('shared_with', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('category', models.CharField(choices=[('blacklist', 'blacklist'), ('whitelist', 'whitelist')], max_length=255)),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='persistentsegmentrelatedvideo',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related', to='segment.PersistentSegmentVideo'),
        ),
        migrations.AlterUniqueTogether(
            name='persistentsegmentrelatedvideo',
            unique_together=set([('segment', 'related_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='persistentsegmentrelatedchannel',
            unique_together=set([('segment', 'related_id')]),
        ),
    ]
