# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-28 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0019_auto_20181227_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persistentsegmentrelatedchannel',
            old_name='statistics',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='persistentsegmentrelatedvideo',
            old_name='statistics',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='persistentsegmentrelatedchannel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='persistentsegmentrelatedchannel',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='persistentsegmentrelatedvideo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='persistentsegmentrelatedvideo',
            name='tags',
        ),
    ]
