# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-28 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0020_auto_20181228_0517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persistentsegmentchannel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='persistentsegmentvideo',
            name='category',
        ),
    ]
