# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-03 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0021_auto_20181228_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persistentsegmentrelatedchannel',
            name='related_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='persistentsegmentrelatedvideo',
            name='related_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
