# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-21 16:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0022_auto_20190103_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentsegmentchannel',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='persistentsegmentvideo',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
