# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-24 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0026_auto_20190304_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentsegmentchannel',
            name='thumbnail_image_url',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='persistentsegmentvideo',
            name='thumbnail_image_url',
            field=models.TextField(default=''),
        ),
    ]
