# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-18 22:46
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('segment', '0028_persistentsegmentfileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSegmentFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('download_url', models.TextField(null=True)),
                ('query', django.contrib.postgres.fields.jsonb.JSONField()),
                ('segment_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='customsegmentfileupload',
            unique_together=set([('content_type', 'segment_id')]),
        ),
    ]
