# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-17 22:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0028_persistentsegmentfileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSegmentFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_id', models.BigIntegerField(db_index=True)),
                ('content_type', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(default=None, null=True)),
                ('filename', models.CharField(max_length=200, unique=True)),
                ('query', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
