# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-20 21:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('segment', '0028_persistentsegmentfileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statistics', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('list_type', models.IntegerField(choices=[(0, 'whitelist'), (1, 'blacklist')])),
                ('segment_type', models.IntegerField(choices=[(0, 'video'), (1, 'channel')])),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomSegmentFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(db_index=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('download_url', models.TextField(null=True)),
                ('query', django.contrib.postgres.fields.jsonb.JSONField()),
                ('updated_at', models.DateTimeField(db_index=True, null=True)),
                ('segment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='export',
                                                 to='segment.CustomSegment')),
            ],
        ),
        migrations.CreateModel(
            name='CustomSegmentRelated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_id', models.CharField(max_length=100)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related',
                                              to='segment.CustomSegment')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='customsegmentrelated',
            unique_together=set([('segment', 'related_id')]),
        ),
    ]
