# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-17 22:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('segment', '0029_customsegmentfileupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customsegmentfileupload',
            name='segment_id',
        ),
        migrations.AddField(
            model_name='customsegmentfileupload',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
