# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-21 00:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('segment', '0029_auto_20190620_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsegment',
            name='title',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='customsegment',
            unique_together=set([('owner', 'title')]),
        ),
    ]
