# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-19 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0030_auto_20190619_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsegmentfileupload',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
