# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-24 18:28
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('segment', '0031_auto_20190624_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsegment',
            name='segment_type',
            field=models.IntegerField(choices=[(0, 'video'), (1, 'channel')], db_index=True),
        ),
    ]
