# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-08 21:41
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('segment', '0032_auto_20190624_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsegment',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
