# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-19 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0034_auto_20190718_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentsegmentchannel',
            name='is_master',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persistentsegmentvideo',
            name='is_master',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
