# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-16 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0032_auto_20190816_1902'),
        ('segment', '0037_auto_20190815_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentsegmentchannel',
            name='audit_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='channel_segment', to='audit_tool.AuditCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persistentsegmentvideo',
            name='audit_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='video_segment', to='audit_tool.AuditCategory'),
            preserve_default=False,
        ),
    ]
