# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-15 18:14
from __future__ import unicode_literals

from django.db import migrations

from es_components.constants import Sections
from es_components.managers import ChannelManager
from es_components.managers import VideoManager


def migrate_segments(apps, schema_editor):
    segments_models = [
        ("PersistentSegmentChannel", ChannelManager),
        ("PersistentSegmentVideo", VideoManager),
    ]

    for segment_model_name, es_manager_cls in segments_models:
        segment_model = apps.get_model(f"segment.{segment_model_name}")
        es_manager = es_manager_cls(sections=[Sections.SEGMENTS], upsert_sections=[Sections.SEGMENTS])
        for segment in segment_model.objects.all():
            related_ids = segment.related.all().values_list("related_id", flat=True)
            es_items = es_manager.get(related_ids)
            for es_item in es_items:
                es_item.populate_segments(uuid=sorted(list(
                    set(es_item.segments.uuid if es_item.segments else {})
                    | {str(segment.uuid)}
                )))
            es_manager.upsert(es_items)

class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0037_auto_20190815_1715'),
    ]

    operations = [
        migrations.RunPython(migrate_segments),
    ]
