# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-16 22:37
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('segment', '0038_auto_20190816_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persistentsegmentchannel',
            name='audit_category',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persistentsegmentvideo',
            name='audit_category',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
