# Generated by Django 2.2.4 on 2019-08-23 11:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('segment', '0040_auto_20190820_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsegment',
            name='statistics',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='persistentsegmentchannel',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='persistentsegmentrelatedchannel',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='persistentsegmentrelatedvideo',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='persistentsegmentvideo',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
