# Generated by Django 2.2.4 on 2019-09-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0041_fix_default_value_for_json_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persistentsegmentchannel',
            name='audit_category',
        ),
        migrations.RemoveField(
            model_name='persistentsegmentvideo',
            name='audit_category',
        ),
        migrations.AddField(
            model_name='persistentsegmentchannel',
            name='audit_category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persistentsegmentvideo',
            name='audit_category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
