# Generated by Django 2.2.4 on 2020-02-26 22:24

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('segment', '0044_customsegment_is_vetting_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSegmentVettedFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('download_url', models.TextField(null=True)),
                ('segment',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vetted_export',
                                      to='segment.CustomSegment')),
            ],
        ),
    ]
