# Generated by Django 3.0.4 on 2020-06-04 08:01

import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models

import segment.models.constants


class Migration(migrations.Migration):
    dependencies = [
        ('segment', '0046_auto_20200513_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsegment',
            name='list_type',
            field=models.IntegerField(choices=[(0, 'whitelist'), (1, 'blacklist')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customsegment',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.CreateModel(
            name='CustomSegmentSourceFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.IntegerField(
                    choices=[[segment.models.constants.SourceListType['INCLUSION'], 'inclusion'],
                             [segment.models.constants.SourceListType['EXCLUSION'], 'exclusion']])),
                ('key', models.TextField()),
                ('segment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source',
                                                 to='segment.CustomSegment')),
            ],
        ),
    ]
