# Generated by Django 3.0.4 on 2020-06-04 23:59

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('segment', '0047_auto_20200604_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsegment',
            name='featured_image_url',
            field=models.TextField(default=''),
        ),
    ]
