# Generated by Django 3.0.4 on 2020-06-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0048_customsegment_featured_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persistentsegmentfileupload',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
