# Generated by Django 3.0.4 on 2020-06-24 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0049_auto_20200615_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customsegmentsourcefileupload',
            old_name='key',
            new_name='filename',
        ),
    ]
