# Generated by Django 3.0.4 on 2020-06-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0050_auto_20200624_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsegmentfileupload',
            name='filename',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customsegmentvettedfileupload',
            name='filename',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customsegmentsourcefileupload',
            name='filename',
            field=models.TextField(null=True),
        ),
    ]
