# Generated by Django 3.0.4 on 2020-08-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0052_auto_20200624_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsegmentsourcefileupload',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
