# Generated by Django 3.0.4 on 2020-08-26 21:10
import datetime

from botocore.exceptions import ClientError
from django.conf import settings
from django.db import migrations

from segment.models.utils.segment_exporter import SegmentExporter
from segment.utils.utils import get_content_disposition


def get_s3_key(segment):
    if hasattr(segment, 'export') and segment.export.filename:
        return segment.export.filename
    return f"{segment.uuid}_export.csv"

def get_vetted_s3_key(segment, suffix=None):
    if hasattr(segment, 'vetted_export') and segment.vetted_export.filename and not suffix:
        return segment.vetted_export.filename
    suffix = f"_{suffix}" if suffix is not None else ""
    return f"{segment.uuid}_vetted_export{suffix}.csv"

def update_content_disposition(segment):
    s3 = SegmentExporter(segment, bucket_name=settings.AMAZON_S3_CUSTOM_SEGMENTS_BUCKET_NAME)
    try:
        key = get_s3_key(segment)
        content_disposition = get_content_disposition(segment)
        s3.copy_from(key, key, ContentDisposition=content_disposition)
    except ClientError:
        pass
    try:
        vetted_key = get_vetted_s3_key(segment)
        vetted_content_disposition = get_content_disposition(segment, is_vetting=True)
        s3.copy_from(vetted_key, vetted_key, ContentDisposition=vetted_content_disposition)
    except ClientError:
        pass

def update_segment_content_disposition(apps, schema_editor):
    """
    re-update segment content dispositions to fix unquoted filenames
    """
    CustomSegment = apps.get_model('segment', 'CustomSegment')

    commit_time = "2020-07-24"
    commit_datetime = datetime.datetime.strptime(commit_time, "%Y-%m-%d").date()
    query = CustomSegment.objects.filter(updated_at__gte=commit_datetime)
    for segment in query:
        update_content_disposition(segment)

class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0053_customsegmentsourcefileupload_name'),
    ]

    operations = [
        migrations.RunPython(update_segment_content_disposition)
    ]
