# Generated by Django 3.0.4 on 2020-10-14 17:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0054_auto_20200826_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsegment',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
