# Generated by Django 3.0.4 on 2020-11-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0056_segmentaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsegmentfileupload',
            name='admin_filename',
            field=models.TextField(default=None, null=True),
        ),
    ]
