# Generated by Django 3.1.6 on 2021-02-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0057_customsegmentfileupload_admin_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsegment',
            name='params',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='customsegment',
            name='statistics',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='customsegmentfileupload',
            name='query',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='persistentsegmentchannel',
            name='details',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='persistentsegmentrelatedchannel',
            name='details',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='persistentsegmentrelatedvideo',
            name='details',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='persistentsegmentvideo',
            name='details',
            field=models.JSONField(default=dict),
        ),
    ]
