# Generated by Django 3.1.7 on 2021-03-25 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('segment', '0058_auto_20210202_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParamsTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segment_type', models.IntegerField(choices=[(0, 'video'), (1, 'channel')], db_index=True)),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('title_hash', models.BigIntegerField(db_index=True, default=0)),
                ('params', models.JSONField(default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
