# Generated by Django 3.1.7 on 2021-03-30 20:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('segment', '0059_paramstemplate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paramstemplate',
            unique_together={('title', 'owner', 'segment_type')},
        ),
    ]
