# Generated by Django 3.1.6 on 2021-03-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0060_auto_20210330_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsegment',
            name='gads_is_synced',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
    ]
