# Generated by Django 3.1.6 on 2021-04-06 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_account_name'),
        ('segment', '0061_customsegment_gads_is_synced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customsegment',
            name='gads_is_synced',
        ),
        migrations.CreateModel(
            name='SegmentAdGroupSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('adgroup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gads_sync', to='oauth.adgroup')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gads_sync', to='segment.customsegment')),
            ],
            options={
                'unique_together': {('segment', 'adgroup')},
            },
        ),
    ]
