# Generated by Django 3.1.6 on 2021-04-01 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_account_name'),
        ('segment', '0061_customsegment_gads_is_synced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customsegment',
            name='gads_is_synced',
        ),
        migrations.CreateModel(
            name='SegmentSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(default=dict)),
                ('is_synced', models.BooleanField(db_index=True, default=None, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync', to='oauth.account')),
                ('segment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync', to='segment.customsegment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
