PREDEFINED_QUERIES = [
    "Hobbies & Interests",
    "Alcoholic Beverages",
    "Arts & Entertainment",
    "Automotive",
    "Business",
    "CPG",
    "Education",
    "Energy Oil/Gas",
    "Food & Drink",
    "Health & Fitness",
    "Home & Garden",
    "Law, Govt & Politics",
    "Personal Finance",
    "Pets",
    "Real Estate",
    "Shopping",
    "Society",
    "Sports",
    "Style & Fashion",
    "Technology & Computing",
    "Telecommunication",
    "Travel",
]
