# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-03 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BadWord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(max_length=80)),
            ],
        ),
    ]
