# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-10 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_safety', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('youtube_id', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=80)),
                ('thumbnail_url', models.URLField()),
                ('category', models.CharField(max_length=80)),
                ('reason', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='badchannel',
            unique_together=set([('youtube_id', 'category')]),
        ),
    ]
