# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-15 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand_safety', '0002_add_bad_channel'),
        ('brand_safety', '0002_add_bad_video'),
    ]

    operations = [
    ]
