# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-25 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_safety', '0003_merge_20181215_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='badchannel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
