# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-01 18:27
from __future__ import unicode_literals

from django.db import migrations


def add_brand_safety_categories(apps, schema_editor):
    BadWord = apps.get_model("brand_safety", "BadWord")
    BadWordCategory = apps.get_model("brand_safety", "BadWordCategory")

    for word in BadWord.objects.all():
        word.category_ref = BadWordCategory.from_string(word.category)
        word.save()


class Migration(migrations.Migration):

    dependencies = [
        ('brand_safety', '0005_auto_20190401_1817'),
    ]

    operations = [
        migrations.RunPython(add_brand_safety_categories),
    ]
