# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-10 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_safety', '0006_add_bad_word_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='badword',
            name='negative_score',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
