# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-16 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand_safety', '0007_badword_negative_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badword',
            name='category_ref',
        ),
        migrations.AlterField(
            model_name='badword',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='brand_safety.BadWordCategory'),
        ),
    ]
