# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-15 21:00
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('brand_safety', '0007_badword_negative_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badword',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
