# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-16 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('brand_safety', '0009_auto_20190515_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badword',
            old_name='category_ref',
            new_name='category',
        ),
        migrations.AlterUniqueTogether(
            name='badword',
            unique_together=set([('name', 'category')]),
        ),
    ]
