# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-20 16:55
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('brand_safety', '0010_auto_20190516_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badword',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE,
                                    to='brand_safety.BadWordCategory'),
            preserve_default=False,
        ),
    ]
