# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-23 22:09
from __future__ import unicode_literals

import brand_safety.models.bad_word
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('brand_safety', '0011_auto_20190520_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadWordLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='badword',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='badword',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='badword',
            name='language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='brand_safety.BadWordLanguage'),
        ),
        migrations.AlterUniqueTogether(
            name='badword',
            unique_together=set([('name', 'category', 'language')]),
        ),
    ]
