# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-24 18:33
from __future__ import unicode_literals

import brand_safety.models.bad_word
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand_safety', '0012_auto_20190523_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badword',
            name='language',
            field=models.ForeignKey(default=brand_safety.models.bad_word.get_default_language, on_delete=django.db.models.deletion.CASCADE, related_name='bad_words', to='brand_safety.BadWordLanguage'),
        ),
        migrations.AlterField(
            model_name='badword',
            name='name',
            field=models.CharField(db_index=True, max_length=80),
        ),
    ]
