# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-30 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0023_auditchannelmeta_video_count'),
        ('brand_safety', '0012_auto_20190529_0001'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='badword',
            unique_together=set([('name', 'language')]),
        ),
    ]
