# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-28 21:55
from __future__ import unicode_literals

import brand_safety.models.bad_word
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand_safety', '0013_auto_20190524_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badword',
            name='language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bad_words', to='audit_tool.AuditLanguage'),
        ),
        migrations.DeleteModel(
            name='BadWordLanguage',
        ),
    ]
