# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-17 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand_safety', '0013_auto_20190530_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadWordHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand_safety.BadWord')),
            ],
        ),
    ]
