# Generated by Django 2.2.4 on 2019-09-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_safety', '0019_brandsafetyflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='badword',
            name='comment_scoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='badword',
            name='meta_scoring',
            field=models.BooleanField(default=True),
        ),
    ]
