# Generated by Django 2.2.4 on 2019-09-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_safety', '0020_auto_20190925_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badword',
            name='comment_scoring',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='badword',
            name='meta_scoring',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
