# Generated by Django 3.0.4 on 2020-09-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_safety', '0020_auto_20190930_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='badwordcategory',
            name='vettable',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
