# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-16 12:50
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_creation', '0002_load_languages_from_fixture'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdGroupOptimizationTuning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi', models.CharField(choices=[('impressions', 'impressions'), ('video_views', 'video_views'), ('clicks', 'clicks'), ('cost', 'cost'), ('ctr', 'ctr'), ('average_cpv', 'average_cpv'), ('video_view_rate', 'video_view_rate'), ('conversions', 'conversions'), ('view_through', 'view_through')], max_length=20)),
                ('value', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_tuning', to='aw_creation.AdGroupCreation')),
            ],
            options={
                'abstract': False,
                'ordering': ['item'],
            },
        ),
        migrations.CreateModel(
            name='CampaignOptimizationTuning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi', models.CharField(choices=[('impressions', 'impressions'), ('video_views', 'video_views'), ('clicks', 'clicks'), ('cost', 'cost'), ('ctr', 'ctr'), ('average_cpv', 'average_cpv'), ('video_view_rate', 'video_view_rate'), ('conversions', 'conversions'), ('view_through', 'view_through')], max_length=20)),
                ('value', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_tuning', to='aw_creation.CampaignCreation')),
            ],
            options={
                'abstract': False,
                'ordering': ['item'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='campaignoptimizationtuning',
            unique_together=set([('item', 'kpi')]),
        ),
        migrations.AlterUniqueTogether(
            name='adgroupoptimizationtuning',
            unique_together=set([('item', 'kpi')]),
        ),
    ]
