# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-22 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aw_creation', '0003_auto_20170516_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adgroupcreation',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='campaigncreation',
            options={'ordering': ['-id']},
        ),
    ]
