# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-29 12:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_creation', '0004_auto_20170522_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcreation',
            name='name',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator("^[^#']*$", "# and ' are not allowed for titles")]),
        ),
        migrations.AlterField(
            model_name='adgroupcreation',
            name='name',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator("^[^#']*$", "# and ' are not allowed for titles")]),
        ),
        migrations.AlterField(
            model_name='campaigncreation',
            name='name',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator("^[^#']*$", "# and ' are not allowed for titles")]),
        ),
    ]
