# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-01 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_creation', '0005_auto_20170529_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcreation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
