# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-02 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aw_creation', '0006_accountcreation_is_deleted'),
        ('aw_creation', '0005_auto_20170602_0651'),
    ]

    operations = [
    ]
