# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-12 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_creation', '0007_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcreation',
            name='read_only',
            field=models.BooleanField(default=False),
        ),
    ]
