# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-20 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aw_creation', '0008_accountcreation_read_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountcreation',
            name='read_only',
        ),
    ]
