# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-17 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_creation', '0011_auto_20170714_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountcreation',
            name='aw_manager_id',
        ),
        migrations.AddField(
            model_name='adgroupcreation',
            name='max_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
