# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-28 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_creation', '0014_auto_20170726_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncreation',
            name='content_exclusions_raw',
            field=models.CharField(default='["VIDEO_RATING_DV_MA", "VIDEO_NOT_YET_RATED"]', max_length=200),
        ),
    ]
