# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-28 09:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_creation', '0015_auto_20170728_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adcreation',
            name='tracking_template',
            field=models.CharField(blank=True, max_length=250, null=True, validators=[django.core.validators.RegexValidator('(https?://\\S+)|(\\{lpurl\\}\\S*)', 'Tracking url template must ba a valid URL or start with {lpurl} tag')]),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='video_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^(?:https?:/{2})?(?:w{3}\\.)?youtu(?:be)?\\.(?:com|be)(?:/watch\\?v=|/video/)([^\\s&]+)$', 'Wrong video url')]),
        ),
    ]
