# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-28 09:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_creation', '0016_auto_20170728_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adcreation',
            name='display_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='final_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='tracking_template',
            field=models.CharField(default='', max_length=250, validators=[django.core.validators.RegexValidator('(https?://\\S+)|(\\{lpurl\\}\\S*)', 'Tracking url template must ba a valid URL or start with {lpurl} tag')]),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='video_channel_title',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='video_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='video_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='video_thumbnail',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='video_title',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='video_url',
            field=models.URLField(default='', validators=[django.core.validators.RegexValidator('^(?:https?:/{2})?(?:w{3}\\.)?youtu(?:be)?\\.(?:com|be)(?:/watch\\?v=|/video/)([^\\s&]+)$', 'Wrong video url')]),
        ),
    ]
