# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-14 12:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_creation', '0017_auto_20170728_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcreation',
            name='sync_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='adgroupcreation',
            name='sync_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='campaigncreation',
            name='sync_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='video_url',
            field=models.URLField(default='', validators=[django.core.validators.RegexValidator('^(?:https?:/{2})?(?:w{3}\\.)?youtu(?:be)?\\.(?:com|be)(?:/watch\\?v=|/video/|/)([^\\s&\\?]+)$', 'Wrong video url')]),
        ),
    ]
