# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-16 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aw_creation', '0018_auto_20170814_1252'),
        ('aw_creation', '0018_auto_20170809_0919'),
    ]

    operations = [
    ]
