# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-09-13 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_creation', '0021_auto_20170913_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcreation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adgroupcreation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaigncreation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
