# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-09-19 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_creation', '0022_auto_20170913_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcreation',
            name='video_duration',
            field=models.FloatField(default=0),
        ),
    ]
