# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-11-14 14:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_creation', '0023_adcreation_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcreation',
            name='beacon_completed_1',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='adcreation',
            name='beacon_completed_2',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='adcreation',
            name='beacon_completed_3',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='adcreation',
            name='beacon_dcm_1',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='adcreation',
            name='beacon_dcm_2',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='adcreation',
            name='beacon_dcm_3',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='adcreation',
            name='beacon_first_quartile_1',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='adcreation',
            name='beacon_first_quartile_2',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='adcreation',
            name='beacon_first_quartile_3',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='adcreation',
            name='beacon_impression_1',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='adcreation',
            name='beacon_impression_2',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='adcreation',
            name='beacon_impression_3',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='adcreation',
            name='beacon_midpoint_1',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='adcreation',
            name='beacon_midpoint_2',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='adcreation',
            name='beacon_midpoint_3',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='adcreation',
            name='beacon_skip_1',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='adcreation',
            name='beacon_skip_2',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='adcreation',
            name='beacon_skip_3',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='adcreation',
            name='beacon_third_quartile_1',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='adcreation',
            name='beacon_third_quartile_2',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='adcreation',
            name='beacon_third_quartile_3',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='adcreation',
            name='beacon_vast_1',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='adcreation',
            name='beacon_vast_2',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='adcreation',
            name='beacon_vast_3',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='adcreation',
            name='beacon_view_1',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='adcreation',
            name='beacon_view_2',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='adcreation',
            name='beacon_view_3',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='video_url',
            field=models.URLField(default='', validators=[django.core.validators.RegexValidator('^(?:https?:/{2})?(?:w{3}\\.)?youtu(?:be)?\\.(?:com|be)(?:/watch\\?v=|/video/|/)([^\\s&/\\?]+)(?:.*)$', 'Wrong video url')]),
        ),
    ]
