# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-11-21 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0016_auto_20171121_1230'),
        ('aw_creation', '0024_auto_20171114_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcreation',
            name='ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_creation', to='aw_reporting.Ad'),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='beacon_completed_1',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='beacon_completed_2',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='beacon_completed_3',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='beacon_dcm_1',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='beacon_dcm_2',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='beacon_dcm_3',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='beacon_first_quartile_1',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='beacon_first_quartile_2',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='beacon_first_quartile_3',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='beacon_impression_1',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='beacon_impression_2',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='beacon_impression_3',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='beacon_midpoint_1',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='beacon_midpoint_2',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='beacon_midpoint_3',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='beacon_skip_1',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='beacon_skip_2',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='beacon_skip_3',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='beacon_third_quartile_1',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='beacon_third_quartile_2',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='beacon_third_quartile_3',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='beacon_vast_1',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='beacon_vast_2',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='beacon_vast_3',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='beacon_view_1',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='beacon_view_2',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='beacon_view_3',
            field=models.URLField(blank=True, default=''),
        ),
    ]
