# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-13 10:04
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('aw_creation', '0026_auto_20171121_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcreation',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='aw_account_creations', to=settings.AUTH_USER_MODEL),
        ),

    ]
