# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-13 10:04
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def remove_extra_account_creations(apps, schema_editor):
    account_creation_model = apps.get_model('aw_creation.AccountCreation')
    account_creation_model.objects.filter(account__isnull=False, is_managed=False).delete()
    account_creation_model.objects.filter(account__isnull=True).delete()


def add_missing_account_creations(apps, schema_editor):
    account_creation_model = apps.get_model('aw_creation.AccountCreation')
    account_model = apps.get_model('aw_reporting.Account')
    account_with_no_account_creation = account_model.objects \
        .annotate(account_creations_count=Count("account_creations")) \
        .filter(account_creations_count=0)
    bulk_create = [
        account_creation_model(account=account, is_managed=False, owner=None)
        for account in account_with_no_account_creation
    ]
    account_creation_model.objects.bulk_create(bulk_create)


class Migration(migrations.Migration):
    dependencies = [
        ('aw_creation', '0026_auto_20171121_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcreation',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='aw_account_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(remove_extra_account_creations),
        migrations.RunPython(add_missing_account_creations),
        migrations.AlterField(
            model_name='accountcreation',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='account_creation', to='aw_reporting.Account'),
        ),
    ]
