# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-18 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aw_creation', '0030_add_missing_account_creations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountoptimizationsetting',
            name='item',
        ),
        migrations.RemoveField(
            model_name='campaignoptimizationsetting',
            name='item',
        ),
        migrations.DeleteModel(
            name='AccountOptimizationSetting',
        ),
        migrations.DeleteModel(
            name='CampaignOptimizationSetting',
        ),
    ]
