# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-03 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_creation', '0032_campaigncreation_budget_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncreation',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
