# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-05 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_creation', '0034_increase_account_name_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncreation',
            name='bid_strategy_type',
            field=models.CharField(choices=[('CPV', 'Maximum CPV'), ('CPM', 'Target CPM'), ('CPA', 'Target CPA')], default='CPV', max_length=3),
        ),
    ]