# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-05 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_creation', '0034_increase_account_name_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcreation',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='adgroupcreation',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='campaigncreation',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
