# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-05 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aw_creation', '0035_add_bid_strategy_type_choice'),
        ('aw_creation', '0035_remove_name_validation'),
    ]

    operations = [
    ]
