# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-08 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_creation', '0037_add_discovery_specific_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncreation',
            name='target_cpa',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
