# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-12 06:51
from __future__ import unicode_literals

from django.db import migrations, models


def change_bid_strategy_values(apps, schema_editor):
    """
    Change existing CampaignCreations with CPV Bid Strategy Type to MAX_CPV
    Change existing CampaignCreations with CPA Bid Strategy Type to TARGET_CPA
    Change existing CampaignCreations with CPM Bid Strategy Type to TARGET_CPM
    """
    campaign_creation_model = apps.get_model('aw_creation.CampaignCreation')

    campaign_creation_model.objects.filter(bid_strategy_type='CPV').update(bid_strategy_type='MAX_CPV')
    campaign_creation_model.objects.filter(bid_strategy_type='CPA').update(bid_strategy_type='TARGET_CPA')
    campaign_creation_model.objects.filter(bid_strategy_type='CPM').update(bid_strategy_type='TARGET_CPM')


class Migration(migrations.Migration):


    dependencies = [
        ('aw_creation', '0038_campaigncreation_target_cpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncreation',
            name='bid_strategy_type',
            field=models.CharField(choices=[('MAX_CPV', 'Maximum CPV'), ('MAX_CPM', 'Maximum CPM'), ('TARGET_CPM', 'Target CPM'), ('TARGET_CPA', 'Target CPA')], default='MAX_CPV', max_length=10),
        ),
        migrations.RunPython(change_bid_strategy_values)
    ]
