# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-21 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_creation', '0040_auto_20190213_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adcreation',
            name='business_name',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='long_headline',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='adcreation',
            name='short_headline',
            field=models.CharField(default='', max_length=250, null=True),
        ),
    ]
