# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-26 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aw_creation', '0041_auto_20190221_1907'),
        ('aw_creation', '0041_update_short_headline_limit'),
    ]

    operations = [
    ]
