# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-04 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_creation', '0042_merge_20190226_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adcreation',
            name='short_headline',
            field=models.CharField(default='', max_length=25, null=True),
        ),
    ]
