# Generated by Django 2.2.4 on 2020-01-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_creation', '0043_auto_20190304_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcreation',
            name='account',
            field=models.IntegerField(null=True),
        ),
    ]
