# Generated by Django 2.2.4 on 2020-01-28 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aw_creation', '0044_auto_20200128_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcreation',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_creation', to='aw_reporting.Account'),
        ),
    ]
