# Generated by Django 3.0.4 on 2020-05-07 17:15

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('aw_creation', '0045_account_alter_pk_to_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='adgroupcreation',
            name='status',
            field=models.IntegerField(choices=[(0, 'paused'), (1, 'enabled')], db_index=True, default=None, null=True),
        ),
    ]
