# Generated by Django 3.0.4 on 2020-05-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_creation', '0045_account_alter_pk_to_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='adgroupcreation',
            name='status',
            field=models.CharField(choices=[('paused', 'paused'), ('enabled', 'enabled')], default=None, max_length=10, null=True),
        ),
    ]
