# Generated by Django 3.1.6 on 2021-02-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cache', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacheitem',
            name='value',
            field=models.JSONField(default=dict),
        ),
    ]
