# Generated by Django 2.2.4 on 2019-09-24 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aw_reporting', '0059_flightstatistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityTargetingReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('external_link', models.URLField(default=None, null=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aw_reporting.Opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityTargetingReportRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads_analyzer.OpportunityTargetingReport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='opportunitytargetingreportrecipient',
            constraint=models.UniqueConstraint(fields=('report', 'user'), name='unique_recipient_for_report'),
        ),
        migrations.AddConstraint(
            model_name='opportunitytargetingreport',
            constraint=models.UniqueConstraint(fields=('opportunity', 'date_from', 'date_to'), name='unique_id_date_range'),
        ),
    ]
