# Generated by Django 2.2.4 on 2019-10-03 13:55

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('ads_analyzer', '0002_opportunitytargetingreport_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunitytargetingreport',
            name='external_link',
        ),
        migrations.AddField(
            model_name='opportunitytargetingreport',
            name='s3_file_key',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='opportunitytargetingreport',
            name='status',
            field=models.CharField(
                choices=[('IN_PROGRESS', 'in_progress'), ('SUCCESS', 'success'), ('FAILED', 'failed')],
                default='in_progress', max_length=32),
        ),
    ]
