# Generated by Django 2.2.4 on 2019-10-07 14:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ads_analyzer', '0002_opportunitytargetingreport_created_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='opportunitytargetingreport',
            name='unique_id_date_range',
        ),
    ]
