# Generated by Django 2.2.4 on 2019-10-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_analyzer', '0002_opportunitytargetingreport_created_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='opportunitytargetingreport',
            name='unique_id_date_range',
        ),
        migrations.AddField(
            model_name='opportunitytargetingreport',
            name='expire_at',
            field=models.DateField(null=True),
        ),
        migrations.AddConstraint(
            model_name='opportunitytargetingreport',
            constraint=models.UniqueConstraint(fields=('opportunity', 'date_from', 'date_to', 'expire_at'), name='unique_id_date_range'),
        ),
    ]
