# Generated by Django 2.2.4 on 2019-10-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_analyzer', '0005_merge_20191008_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunitytargetingreport',
            name='s3_file_key',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
