# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-13 14:13
from __future__ import unicode_literals

from django.db import migrations
import csv


def load_geo_tagets(apps, schema_editor):
    lang_model = apps.get_model('aw_reporting.GeoTarget')
    with open('aw_reporting/fixtures/geo_locations.csv') as f:
        reader = csv.reader(f)
        next(reader, None)  # title
        bulk = []
        for uid, name, c_name, parent_id, c_code, t_type, status in reader:
            bulk.append(lang_model(
                id=uid, name=name, canonical_name=c_name,
                parent_id=parent_id, country_code=c_code,
                target_type=t_type, status=status,
            ))
        lang_model.objects.bulk_create(bulk)


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_geo_tagets),
    ]
