# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-30 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0006_auto_20170529_1218'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaignstatistic',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='campaignstatistic',
            name='campaign',
        ),
        migrations.AddField(
            model_name='awconnection',
            name='revoked_access',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CampaignStatistic',
        ),
    ]
