# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-06 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0008_auto_20170602_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordstatistic',
            name='keyword',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
