# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-15 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0009_auto_20170606_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
