# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-15 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0010_auto_20170615_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='updated_date',
            field=models.DateField(null=True),
        ),
    ]
