# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-30 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0013_auto_20170703_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='adgroup',
            name='active_view_impressions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='engagements',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adgroupstatistic',
            name='active_view_impressions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adgroupstatistic',
            name='engagements',
            field=models.IntegerField(default=0),
        ),
    ]
