# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-31 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0014_auto_20170830_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='adgroup',
            name='type',
            field=models.CharField(default='', max_length=25),
        ),
    ]
