# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-11-20 12:10
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0015_adgroup_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adgroup',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_groups', to='aw_reporting.Campaign'),
        ),
    ]
