# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-03-29 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0017_ad_is_disapproved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='creative_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='display_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='headline',
            field=models.TextField(null=True),
        ),
    ]
