# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-04-19 10:50
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0023_auto_20180413_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impressions', models.IntegerField(default=0)),
                ('video_views', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('conversions', models.FloatField(default=0)),
                ('all_conversions', models.FloatField(default=0)),
                ('view_through', models.IntegerField(default=0)),
                ('video_views_25_quartile', models.FloatField(default=0)),
                ('video_views_50_quartile', models.FloatField(default=0)),
                ('video_views_75_quartile', models.FloatField(default=0)),
                ('video_views_100_quartile', models.FloatField(default=0)),
                ('date', models.DateField(db_index=True)),
                ('parent_status_id', models.SmallIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='adgroup',
            name='age_18_24',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='age_25_34',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='age_35_44',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='age_45_54',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='age_55_64',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='age_65',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='age_undetermined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='de_norm_fields_are_recalculated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='device_computers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='device_mobile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='device_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='device_tablets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='gender_female',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='gender_male',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='gender_undetermined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='has_channels',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='has_interests',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='has_keywords',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='has_remarketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='has_topics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='has_videos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='max_stat_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='min_stat_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='parent_not_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='parent_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='parent_undetermined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='age_18_24',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='age_25_34',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='age_35_44',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='age_45_54',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='age_55_64',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='age_65',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='age_undetermined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='de_norm_fields_are_recalculated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='device_computers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='device_mobile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='device_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='device_tablets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='gender_female',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='gender_male',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='gender_undetermined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='has_channels',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='has_interests',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='has_keywords',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='has_remarketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='has_topics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='has_videos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='max_stat_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='min_stat_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='parent_not_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='parent_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='parent_undetermined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parentstatistic',
            name='ad_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_statistics', to='aw_reporting.AdGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='parentstatistic',
            unique_together=set([('parent_status_id', 'ad_group', 'date')]),
        ),
    ]
