# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-04-22 13:54
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0024_add_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoTargeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impressions', models.IntegerField(default=0)),
                ('video_views', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('conversions', models.FloatField(default=0)),
                ('all_conversions', models.FloatField(default=0)),
                ('view_through', models.IntegerField(default=0)),
                ('video_views_25_quartile', models.FloatField(default=0)),
                ('video_views_50_quartile', models.FloatField(default=0)),
                ('video_views_75_quartile', models.FloatField(default=0)),
                ('video_views_100_quartile', models.FloatField(default=0)),
                ('is_negative', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_performance', to='aw_reporting.Campaign')),
                ('geo_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_performance', to='aw_reporting.GeoTarget')),
            ],
            options={
                'ordering': ['campaign', 'geo_target'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='geotargeting',
            unique_together=set([('campaign', 'geo_target')]),
        ),
    ]
