# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-13 14:13
from __future__ import unicode_literals

import csv

from django.db import migrations


def load_data(apps, schema_editor):
    audience_model = apps.get_model('aw_reporting.Audience')
    bulk = []
    with open('aw_reporting/fixtures/affinity_categories-2018-04-26.csv') as f:
        reader = csv.reader(f)
        next(reader, None)  # title
        for uid, name in reader:
            bulk.append(audience_model(
                id=uid, name=name, type="affinity",
            ))
    with open('aw_reporting/fixtures/in-market_categories-2018-04-26.csv') as f:
        reader = csv.reader(f)
        next(reader, None)  # title
        for uid, name in reader:
            bulk.append(audience_model(
                id=uid, name=name, type="in-market",
            ))
    audience_model.objects.bulk_create(bulk)

class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0024_add_statistics.py'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]
