# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-05-03 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0027_load_audience_20180426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geotarget',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
