# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-05-03 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0028_auto_20180503_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='hourly_updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='settings_updated_time',
            field=models.DateTimeField(null=True),
        ),
    ]
