# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-05-03 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0029_auto_20180503_1505'),
        ('aw_reporting', '0002_load_geo_targets_from_fixture'),
    ]

    operations = [
    ]
