# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-05-16 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0030_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='placement_code',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
