# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-05-17 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0031_campaign_placement_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opplacement',
            name='number',
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
    ]
