# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-05-18 18:02
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F, OuterRef, Subquery

from aw_reporting.update.tasks import extract_placement_code


def _set_placement_code(apps, schema_editor):
    Campaign = apps.get_model("aw_reporting", "Campaign")
    db_alias = schema_editor.connection.alias
    campaigns = Campaign.objects.using(db_alias).all()

    for campaign in campaigns:
        campaign.placement_code = extract_placement_code(campaign.name)
        campaign.save()


def _match_using_placement_numbers(apps, schema_editor):
    Campaign = apps.get_model("aw_reporting", "Campaign")
    OpPlacement = apps.get_model("aw_reporting", "OpPlacement")
    db_alias = schema_editor.connection.alias

    placements = OpPlacement.objects.using(db_alias) \
                     .filter(number=OuterRef("placement_code")) \
                     .values("pk")[:1]
    campaigns = Campaign.objects.using(db_alias) \
        .filter(placement_code__isnull=False) \
        .annotate(placement_id=Subquery(placements))
    campaigns.update(salesforce_placement_id=F("placement_id"))


def _fix_links(apps, schema_editor):
    _set_placement_code(apps, schema_editor)
    _match_using_placement_numbers(apps, schema_editor)


class Migration(migrations.Migration):
    dependencies = [
        ('aw_reporting', '0034_auto_20180518_1338'),
    ]

    operations = [
        migrations.RunPython(_fix_links, lambda *_: None)
    ]
