# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-07 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0036_auto_20180830_1347'),
        ('aw_reporting', '0036_account_is_active'),
    ]

    operations = [
    ]
