# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-19 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0046_add_cta_to_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='budget_type',
            field=models.CharField(default='daily', max_length=30),
        ),
    ]
