# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-18 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0046_add_cta_to_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='region_id',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='territory',
            field=models.CharField(default=None, max_length=80, null=True),
        ),
    ]
