# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-20 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0047_update_territory'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='margin_cap_required',
            field=models.BooleanField(default=False),
        ),
    ]
