# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-03 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0047_campaign_budget_type'),
        ('aw_reporting', '0048_opportunity_margin_cap_required'),
    ]

    operations = [
    ]
