# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-09 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0049_merge_20190103_1316'),
        ('aw_reporting', '0048_update_billing_servers'),
    ]

    operations = [
    ]
