# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-05 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0050_increase_account_name_length'),
        ('aw_reporting', '0050_merge_20190109_1501'),
    ]

    operations = [
    ]
