# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-08 18:40
from __future__ import unicode_literals

from django.db import migrations, models
from aw_reporting.models import Opportunity


def set_opportunity_buffers_none(apps, schema_editor):
    Opportunity.objects.filter(cpv_buffer=0).update(cpv_buffer=None)
    Opportunity.objects.filter(cpm_buffer=0).update(cpm_buffer=None)


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0055_flight_pacing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='cpm_buffer',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='cpv_buffer',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.RunPython(set_opportunity_buffers_none)
    ]

