# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-26 13:36
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("aw_reporting", "0056_auto_20190408_1840"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="ad_count",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="account",
            name="channel_count",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="account",
            name="interest_count",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="account",
            name="keyword_count",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="account",
            name="topic_count",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="account",
            name="video_count",
            field=models.BigIntegerField(default=0),
        ),
    ]
