# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-07 13:44
from __future__ import unicode_literals

from django.db import migrations


def remove_old_demo_opportunity(apps, schema_editor):
    opportunity_model = apps.get_model('aw_reporting.Opportunity')
    opportunity_model.objects.filter(id="").delete()


class Migration(migrations.Migration):
    dependencies = [
        ('aw_reporting', '0057_account_denorm_stats'),
    ]

    operations = [
        migrations.RunPython(remove_old_demo_opportunity)
    ]
