# Generated by Django 2.2.4 on 2019-08-30 14:40

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("aw_reporting", "0058_remove_demo_opportunity"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightStatistic",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("delivery", models.IntegerField(default=0)),
                ("impressions", models.IntegerField(default=0)),
                ("video_impressions", models.IntegerField(default=0)),
                ("video_clicks", models.IntegerField(default=0)),
                ("video_cost", models.FloatField(default=0)),
                ("video_views", models.IntegerField(default=0)),
                ("clicks", models.IntegerField(default=0)),
                ("sum_cost", models.FloatField(default=0)),
                ("flight", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="statistic",
                                                to="aw_reporting.Flight")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
