# Generated by Django 2.2.4 on 2019-09-25 10:21

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("aw_reporting", "0059_flightstatistic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignhourlystatistic",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
