# Generated by Django 2.2.4 on 2019-09-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0060_increase_hourly_statistic_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adgroup',
            name='de_norm_fields_are_recalculated',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='adgroup',
            name='type',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='de_norm_fields_are_recalculated',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
