# Generated by Django 2.2.4 on 2019-10-18 22:01

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("aw_reporting", "0063_change_campaign_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="aw_cid",
            field=models.CharField(db_index=True, max_length=60, null=True),
        ),
    ]
