# Generated by Django 2.2.4 on 2019-10-30 07:02

from django.db import migrations


def change_enum_to_str(apps, schema_editor):
    AdGroupStatistic = apps.get_model('aw_reporting', 'AdGroupStatistic')
    AdGroupStatistic.objects.filter(ad_network="0").update(ad_network="unspecified")
    AdGroupStatistic.objects.filter(ad_network="1").update(ad_network="unknown")
    AdGroupStatistic.objects.filter(ad_network="2").update(ad_network="Search Network")
    AdGroupStatistic.objects.filter(ad_network="3").update(ad_network="Search Partners")
    AdGroupStatistic.objects.filter(ad_network="4").update(ad_network="Display Network")
    AdGroupStatistic.objects.filter(ad_network="5").update(ad_network="YouTube Search")
    AdGroupStatistic.objects.filter(ad_network="6").update(ad_network="YouTube Videos")
    AdGroupStatistic.objects.filter(ad_network="7").update(ad_network="Cross-network")


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0064_auto_20191018_2201'),
    ]

    operations = [
        migrations.RunPython(change_enum_to_str),
    ]
