# Generated by Django 2.2.4 on 2019-11-07 01:10

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("aw_reporting", "0065_change_ad_network_enum"),
    ]

    operations = [
        migrations.AddField(
            model_name="ytchannelstatistic",
            name="placement_type",
            field=models.IntegerField(choices=[(0, "Managed"), (1, "Group")], db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="ytvideostatistic",
            name="placement_type",
            field=models.IntegerField(choices=[(0, "Managed"), (1, "Group")], db_index=True, default=0),
        ),
        migrations.AlterUniqueTogether(
            name="ytchannelstatistic",
            unique_together={("ad_group", "yt_id", "device_id", "date", "placement_type")},
        ),
        migrations.AlterUniqueTogether(
            name="ytvideostatistic",
            unique_together={("ad_group", "yt_id", "device_id", "date", "placement_type")},
        ),
    ]
