# Generated by Django 2.2.4 on 2020-01-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0067_auto_20191216_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='start',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
