# Generated by Django 2.2.4 on 2020-01-15 21:03

from django.db import migrations


# Change all ad group types to Adword API adgroup type constants for consistency
# https://developers.google.com/adwords/api/docs/appendix/reports/adgroup-performance-report#adgrouptype
def change_ad_group_type(apps, schema_editor):
    AdGroup = apps.get_model("aw_reporting", "AdGroup")

    AdGroup.objects.filter(type__iexact="SEARCH_STANDARD").update(type="Standard")
    AdGroup.objects.filter(type__iexact="DISPLAY_STANDARD").update(type="Display")
    AdGroup.objects.filter(type__iexact="VIDEO_TRUE_VIEW_IN_STREAM").update(type="In-stream")
    AdGroup.objects.filter(type__iexact="VIDEO_TRUE_VIEW_IN_DISPLAY").update(type="Video Discovery")
    AdGroup.objects.filter(type__iexact="VIDEO_BUMPER").update(type="Bumper")
    AdGroup.objects.filter(type__iexact="VIDEO_NON_SKIPPABLE_IN_STREAM").update(type="Standard")


class Migration(migrations.Migration):
    dependencies = [
        ("aw_reporting", "0068_auto_20200110_1755"),
    ]

    operations = [
        migrations.RunPython(change_ad_group_type)
    ]
