# Generated by Django 2.2.4 on 2020-01-15 21:24

from django.db import migrations


def change_opportunity_territory(apps, schema_editor):
    Opportunity = apps.get_model("aw_reporting", "Opportunity")
    Opportunity.objects.filter(territory="West / Northwest").update(territory="US - West / Northwest")


class Migration(migrations.Migration):
    dependencies = [
        ("aw_reporting", "0069_ad_group_type_data_migration"),
    ]

    operations = [
        migrations.RunPython(change_opportunity_territory)
    ]
