# Generated by Django 2.2.4 on 2020-01-16 18:59

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("aw_reporting", "0070_salesforce_opportunity_territory_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opplacement",
            name="end",
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="opplacement",
            name="start",
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="end",
            field=models.DateField(db_index=True, null=True),
        ),
    ]
