# Generated by Django 2.2.4 on 2020-01-16 19:05

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("aw_reporting", "0071_auto_20200116_1859"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="apex_deal",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
