# Generated by Django 2.2.4 on 2020-01-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0074_auto_20200116_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='brand',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='types_of_targeting',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
    ]
