# Generated by Django 2.2.4 on 2020-01-16 19:41

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("aw_reporting", "0075_auto_20200116_1925"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="budget",
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="cannot_roll_over",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="cpm_buffer",
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="cpm_cost",
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="cpv_buffer",
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="cpv_cost",
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="goal_type_id",
            field=models.SmallIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="impressions",
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="margin_cap_required",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="number",
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="probability",
            field=models.PositiveSmallIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="territory",
            field=models.CharField(db_index=True, default=None, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="video_views",
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
