# Generated by Django 2.2.4 on 2020-01-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0076_auto_20200116_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opplacement',
            name='goal_type_id',
            field=models.SmallIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='opplacement',
            name='ordered_rate',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='opplacement',
            name='tech_fee',
            field=models.DecimalField(db_index=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='opplacement',
            name='total_cost',
            field=models.FloatField(db_index=True, null=True),
        ),
    ]
