# Generated by Django 2.2.4 on 2020-01-16 20:15

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("aw_reporting", "0077_auto_20200116_1945"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opplacement",
            name="tech_fee_type",
            field=models.CharField(choices=[("CPV", "CPV"), ("CPM", "CPM")], db_index=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="ad_ops_email",
            field=models.EmailField(db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="am_email",
            field=models.EmailField(db_index=True, max_length=254, null=True),
        ),
    ]
