# Generated by Django 2.2.4 on 2020-01-16 20:26

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("aw_reporting", "0078_auto_20200116_2015"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="ad_count",
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="account",
            name="can_manage_clients",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="account",
            name="channel_count",
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="account",
            name="interest_count",
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_test_account",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="account",
            name="keyword_count",
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="account",
            name="managers",
            field=models.ManyToManyField(db_index=True, related_name="_account_managers_+", to="aw_reporting.Account"),
        ),
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="topic_count",
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="account",
            name="update_time",
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="video_count",
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="account",
            name="visible",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
