# Generated by Django 2.2.4 on 2020-01-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0079_auto_20200116_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='budget',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='cost',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='delivered',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='end',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='flight',
            name='ordered_cost',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='ordered_units',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='start',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='total_cost',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightstatistic',
            name='clicks',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='flightstatistic',
            name='delivery',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='flightstatistic',
            name='impressions',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='flightstatistic',
            name='sum_cost',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='flightstatistic',
            name='video_clicks',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='flightstatistic',
            name='video_cost',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='flightstatistic',
            name='video_impressions',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='flightstatistic',
            name='video_views',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='sfaccount',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
