# Generated by Django 2.2.4 on 2020-01-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0080_auto_20200117_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='all_conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='ad',
            name='clicks',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='ad',
            name='conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='ad',
            name='impressions',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='ad',
            name='is_disapproved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='video_views',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='ad',
            name='view_through',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='adgroup',
            name='active_view_impressions',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='adgroup',
            name='all_conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='adgroup',
            name='clicks',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='adgroup',
            name='conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='adgroup',
            name='cpc_bid',
            field=models.PositiveIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='adgroup',
            name='cpm_bid',
            field=models.PositiveIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='adgroup',
            name='cpv_bid',
            field=models.PositiveIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='adgroup',
            name='engagements',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='adgroup',
            name='impressions',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='adgroup',
            name='max_stat_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='adgroup',
            name='min_stat_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='adgroup',
            name='status',
            field=models.CharField(db_index=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='adgroup',
            name='type',
            field=models.CharField(db_index=True, default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='adgroup',
            name='video_views',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='adgroup',
            name='view_through',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='adgroupstatistic',
            name='all_conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='adgroupstatistic',
            name='clicks',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='adgroupstatistic',
            name='conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='adgroupstatistic',
            name='impressions',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='adgroupstatistic',
            name='video_views',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='adgroupstatistic',
            name='view_through',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='adstatistic',
            name='all_conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='adstatistic',
            name='clicks',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='adstatistic',
            name='conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='adstatistic',
            name='impressions',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='adstatistic',
            name='video_views',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='adstatistic',
            name='view_through',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='agerangestatistic',
            name='all_conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='agerangestatistic',
            name='clicks',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='agerangestatistic',
            name='conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='agerangestatistic',
            name='impressions',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='agerangestatistic',
            name='video_views',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='agerangestatistic',
            name='view_through',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='audiencestatistic',
            name='all_conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='audiencestatistic',
            name='clicks',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='audiencestatistic',
            name='conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='audiencestatistic',
            name='impressions',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='audiencestatistic',
            name='video_views',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='audiencestatistic',
            name='view_through',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='_end',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='_start',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='all_conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='budget',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='clicks',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='impressions',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='max_stat_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='min_stat_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='type',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='video_views',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='view_through',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='campaignstatistic',
            name='all_conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='campaignstatistic',
            name='clicks',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='campaignstatistic',
            name='conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='campaignstatistic',
            name='impressions',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='campaignstatistic',
            name='video_views',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='campaignstatistic',
            name='view_through',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='citystatistic',
            name='all_conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='citystatistic',
            name='clicks',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='citystatistic',
            name='conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='citystatistic',
            name='impressions',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='citystatistic',
            name='video_views',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='citystatistic',
            name='view_through',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='genderstatistic',
            name='all_conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='genderstatistic',
            name='clicks',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='genderstatistic',
            name='conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='genderstatistic',
            name='impressions',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='genderstatistic',
            name='video_views',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='genderstatistic',
            name='view_through',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='geotarget',
            name='country_code',
            field=models.CharField(db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='geotarget',
            name='status',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='geotargeting',
            name='all_conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='geotargeting',
            name='clicks',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='geotargeting',
            name='conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='geotargeting',
            name='impressions',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='geotargeting',
            name='video_views',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='geotargeting',
            name='view_through',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='keywordstatistic',
            name='all_conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='keywordstatistic',
            name='clicks',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='keywordstatistic',
            name='conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='keywordstatistic',
            name='impressions',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='keywordstatistic',
            name='video_views',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='keywordstatistic',
            name='view_through',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='parentstatistic',
            name='all_conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='parentstatistic',
            name='clicks',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='parentstatistic',
            name='conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='parentstatistic',
            name='impressions',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='parentstatistic',
            name='video_views',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='parentstatistic',
            name='view_through',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='remarkstatistic',
            name='all_conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='remarkstatistic',
            name='clicks',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='remarkstatistic',
            name='conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='remarkstatistic',
            name='impressions',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='remarkstatistic',
            name='video_views',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='remarkstatistic',
            name='view_through',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='topicstatistic',
            name='all_conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='topicstatistic',
            name='clicks',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='topicstatistic',
            name='conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='topicstatistic',
            name='impressions',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='topicstatistic',
            name='video_views',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='topicstatistic',
            name='view_through',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='videocreative',
            name='all_conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='videocreative',
            name='clicks',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='videocreative',
            name='conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='videocreative',
            name='duration',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='videocreative',
            name='impressions',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='videocreative',
            name='video_views',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='videocreative',
            name='view_through',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='videocreativestatistic',
            name='all_conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='videocreativestatistic',
            name='clicks',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='videocreativestatistic',
            name='conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='videocreativestatistic',
            name='impressions',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='videocreativestatistic',
            name='video_views',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='videocreativestatistic',
            name='view_through',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='ytchannelstatistic',
            name='all_conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='ytchannelstatistic',
            name='clicks',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='ytchannelstatistic',
            name='conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='ytchannelstatistic',
            name='impressions',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='ytchannelstatistic',
            name='video_views',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='ytchannelstatistic',
            name='view_through',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='ytvideostatistic',
            name='all_conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='ytvideostatistic',
            name='clicks',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='ytvideostatistic',
            name='conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='ytvideostatistic',
            name='impressions',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='ytvideostatistic',
            name='video_views',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='ytvideostatistic',
            name='view_through',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
