# Generated by Django 2.2.4 on 2020-01-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0081_auto_20200124_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
