# Generated by Django 2.2.4 on 2020-01-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0081_auto_20200124_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awaccountpermission',
            name='account',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='account',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
