# Generated by Django 2.2.4 on 2020-01-28 00:19

from django.db import migrations, models


def update_fields(apps, schema_editor):
    # Remove atomicity to be able to save progress of migration if timeout occurs
    schema_editor.atomic.__exit__(None, None, None)
    schema_editor.execute('''
    drop index aw_reporting_campaign_account_id_8e3dadc5_like;
    create index aw_reporting_campaign_account_id_8e3dadc5_like on aw_reporting_campaign(account_id);
    ALTER TABLE aw_reporting_campaign 
        ALTER COLUMN account_id TYPE INTEGER USING CAST(account_id AS INT);
    ''')
#ALTER TABLE aw_reporting_campaign ALTER COLUMN account_id TYPE bigint USING (account_id::integer);
class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0081_auto_20200124_1817'),
    ]

    operations = [
        migrations.RunPython(update_fields),
        # migrations.AlterField(
        #     model_name='account',
        #     name='id',
        #     field=models.BigIntegerField(primary_key=True, serialize=False),
        # ),
    ]
