# Generated by Django 2.2.4 on 2020-01-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0082_auto_20200128_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
