# Generated by Django 2.2.4 on 2020-03-20 23:39

from django.db import migrations, models
import django.db.models.deletion

from aw_reporting.models import CriterionType as criterion_type


def init(apps, schema_editor):
    choices = [choice[0] for choice in criterion_type.NAME_CHOICES]
    CriterionType = apps.get_model("aw_reporting", "CriterionType")
    for choice in choices:
        CriterionType.objects.create(name=choice)


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0086_auto_20200214_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Keyword', 'Keyword'), ('User Interest and List', 'User Interest and List'), ('Vertical', 'Vertical'), ('Gender', 'Gender'), ('Age', 'Age'), ('Placement', 'Placement'), ('Parental status', 'Parental status'), ('Household income', 'Household income'), ('None', 'None'), ('unknown', 'unknown')], db_index=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='adgroup',
            name='criterion_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aw_reporting.CriterionType'),
        ),
        migrations.RunPython(init, reverse_code=reverse)
    ]
