# Generated by Django 3.0.4 on 2020-05-14 00:30

from django.db import migrations, models
import django.db.models.deletion

from aw_reporting.models import CriteriaType as ModelRef
from aw_reporting.models import CriteriaTypeEnum


def init(apps, schema_editor):
    CriteriaType = apps.get_model("aw_reporting", "CriteriaType")
    objs = []
    for type_id in dict(ModelRef.ID_CHOICES).keys():
        objs.append(CriteriaType(id=type_id, name=CriteriaTypeEnum(type_id).name))
    CriteriaType.objects.bulk_create(objs)


def reverse_code(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0088_campaign_bidding_strategy_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdGroupTargeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_negative', models.BooleanField(default=False)),
                ('criteria', models.CharField(max_length=150)),
                ('sync_pending', models.BooleanField(db_index=True, default=False)),
                ('statistic_criteria', models.CharField(db_index=True, max_length=150)),
                ('status', models.IntegerField(choices=[(0, 'paused'), (1, 'enabled'), (2, 'removed')])),
            ],
        ),
        migrations.CreateModel(
            name='CriteriaType',
            fields=[
                ('id', models.IntegerField(choices=[(0, 'Keyword'), (1, 'Placement'), (2, 'Vertical'), (3, 'User List'), (4, 'User Interest'), (5, 'Age Range'), (6, 'Gender'), (7, 'Parental status'), (8, 'Youtube Channel'), (9, 'Youtube Video')], primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='adgroup',
            name='criterion_type',
        ),
        migrations.DeleteModel(
            name='CriterionType',
        ),
        migrations.AddField(
            model_name='adgrouptargeting',
            name='ad_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeting', to='aw_reporting.AdGroup'),
        ),
        migrations.AddField(
            model_name='adgrouptargeting',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aw_reporting.CriteriaType'),
        ),
        migrations.AlterUniqueTogether(
            name='adgrouptargeting',
            unique_together={('ad_group', 'type', 'criteria')},
        ),
        migrations.RunPython(init, reverse_code=reverse_code)
    ]
