# Generated by Django 3.0.4 on 2020-05-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0089_auto_20200514_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='ias_campaign_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
