# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-11-28 17:16
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("aw_reporting", "0092_auto_20200625_2008"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="cost_currency",
            field=models.FloatField(null=True, db_index=True),
        ),
        migrations.AddField(
            model_name="flight",
            name="different_spending_currency",
            field=models.BooleanField(default=False),
        ),
    ]
