# Generated by Django 3.0.4 on 2020-07-13 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aw_reporting', '0093_flight_add_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignBudgetHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sync_at', models.DateTimeField(db_index=True, default=None, null=True)),
                ('budget', models.FloatField()),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_history', to='aw_reporting.Campaign')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
