# Generated by Django 3.0.4 on 2020-07-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0094_campaignhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightpacingallocation',
            name='is_end',
            field=models.BooleanField(default=False),
        ),
    ]
