# Generated by Django 3.0.4 on 2020-07-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0095_flightpacingallocation_is_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='currency_code',
            field=models.CharField(db_index=True, max_length=5, null=True),
        ),
    ]
