# Generated by Django 3.0.4 on 2020-08-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0096_opportunity_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='active_view_viewability',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='active_view_viewability',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='adgroupstatistic',
            name='active_view_viewability',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='adstatistic',
            name='active_view_viewability',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='agerangestatistic',
            name='active_view_viewability',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='audiencestatistic',
            name='active_view_viewability',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='active_view_viewability',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='campaignstatistic',
            name='active_view_viewability',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='citystatistic',
            name='active_view_viewability',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='genderstatistic',
            name='active_view_viewability',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='geotargeting',
            name='active_view_viewability',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='keywordstatistic',
            name='active_view_viewability',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='parentstatistic',
            name='active_view_viewability',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='remarkstatistic',
            name='active_view_viewability',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='topicstatistic',
            name='active_view_viewability',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='videocreative',
            name='active_view_viewability',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='videocreativestatistic',
            name='active_view_viewability',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='ytchannelstatistic',
            name='active_view_viewability',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='ytvideostatistic',
            name='active_view_viewability',
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
