# Generated by Django 3.0.4 on 2020-08-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0096_opportunity_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='active_view_viewability',
            field=models.FloatField(default=True, null=True),
        ),
    ]
