# Generated by Django 3.0.4 on 2020-08-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0097_auto_20200807_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='has_alerts',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
