# Generated by Django 3.0.4 on 2020-08-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0098_opportunity_has_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='all_conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='clicks',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='conversions',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='cost',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='impressions',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='video_views',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='video_views_100_quartile',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='video_views_25_quartile',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='video_views_50_quartile',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='video_views_75_quartile',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='view_through',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='ad',
            name='cost',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='adgroup',
            name='cost',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='adgroupstatistic',
            name='cost',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='adstatistic',
            name='cost',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='agerangestatistic',
            name='cost',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='audiencestatistic',
            name='cost',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='cost',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='campaignstatistic',
            name='cost',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='citystatistic',
            name='cost',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='genderstatistic',
            name='cost',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='geotargeting',
            name='cost',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='keywordstatistic',
            name='cost',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='parentstatistic',
            name='cost',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='remarkstatistic',
            name='cost',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='topicstatistic',
            name='cost',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='videocreative',
            name='cost',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='videocreativestatistic',
            name='cost',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='ytchannelstatistic',
            name='cost',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='ytvideostatistic',
            name='cost',
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
