# Generated by Django 3.0.4 on 2020-09-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0100_account_active_view_viewability'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='margin_cap',
            field=models.FloatField(default=None, null=True),
        ),
    ]
