# Generated by Django 3.0.4 on 2020-11-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0101_flight_margin_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='opplacement',
            name='apex_go_client_rate',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='opplacement',
            name='disney_datorama_placement_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='disney_campaign_advertiser_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
