# Generated by Django 3.0.4 on 2021-01-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0103_citystatistic_bigint'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='creative_tracking_url_template',
            field=models.URLField(default=None, null=True),
        ),
    ]
