# Generated by Django 3.0.4 on 2021-01-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0104_ad_creative_tracking_url_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='creative_tracking_url_template',
            field=models.URLField(default=None, max_length=255, null=True),
        ),
    ]
