# Generated by Django 3.1.6 on 2021-02-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0105_auto_20210122_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignhistory',
            name='changes',
            field=models.JSONField(),
        ),
    ]
