# Generated by Django 3.1.7 on 2021-04-01 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0107_opportunity_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='adgroup',
            name='bidding_strategy_type_id',
            field=models.IntegerField(db_index=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='AdGroupGeoViewStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('device_id', models.SmallIntegerField(db_index=True, default=0)),
                ('impressions', models.IntegerField(db_index=True, default=0)),
                ('video_views', models.IntegerField(db_index=True, default=0)),
                ('clicks', models.IntegerField(db_index=True, default=0)),
                ('cost', models.FloatField(db_index=True, default=0)),
                ('conversions', models.FloatField(db_index=True, default=0)),
                ('all_conversions', models.FloatField(db_index=True, default=0)),
                ('ad_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_view_stats', to='aw_reporting.adgroup')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_geo_view_stats', to='aw_reporting.geotarget')),
                ('metro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metro_geo_view_stats', to='aw_reporting.geotarget')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_geo_view_stats', to='aw_reporting.geotarget')),
            ],
            options={
                'ordering': ['ad_group', 'date', 'device_id'],
                'unique_together': {('ad_group', 'date', 'device_id', 'country', 'region', 'metro')},
            },
        ),
    ]
