# Generated by Django 3.1.7 on 2021-05-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0108_auto_20210401_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('from_code', models.CharField(db_index=True, max_length=3)),
                ('to_code', models.CharField(db_index=True, max_length=3)),
                ('rate', models.DecimalField(decimal_places=15, max_digits=30)),
            ],
        ),
    ]
