# Generated by Django 3.1.6 on 2021-02-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_accountperformance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountperformance',
            name='performance',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='opportunityperformance',
            name='performance',
            field=models.JSONField(default=list),
        ),
    ]
