# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-19 09:38
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViralKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viral_keyword', to='keyword_tool.KeyWord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='keywordslist',
            name='collaborators',
        ),
        migrations.RemoveField(
            model_name='keywordslist',
            name='visible_for_all',
        ),
        migrations.DeleteModel(
            name='Collaborator',
        ),
    ]
