# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-23 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_tool', '0002_auto_20170519_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordslist',
            name='average_cpc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='keywordslist',
            name='average_cpv',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='keywordslist',
            name='average_ctrv',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='keywordslist',
            name='average_view_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='keywordslist',
            name='average_volume',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='keywordslist',
            name='competition',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='keywordslist',
            name='num_keywords',
            field=models.IntegerField(default=0),
        ),
    ]
