# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-24 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_tool', '0003_auto_20170523_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordslist',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
