# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-30 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_tool', '0004_keywordslist_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordslist',
            name='cum_average_volume',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='keywordslist',
            name='cum_average_volume_per_kw',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='keywordslist',
            name='top_keywords',
            field=models.TextField(default='', null=True),
        ),
    ]
