# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-30 17:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_tool', '0005_auto_20170530_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordslist',
            name='cum_average_volume',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keywordslist',
            name='cum_average_volume_per_kw',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keywordslist',
            name='top_keywords',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
