# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-16 12:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_tool', '0006_auto_20170530_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordslist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 6, 16, 12, 22, 45, 464144, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
