# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-10 13:14
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_tool', '0007_keywordslist_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 7, 10, 13, 14, 44, 103372, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
