# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-11-16 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_tool', '0008_keyword_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='daily_views',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='keyword',
            name='thirty_days_views',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='keyword',
            name='weekly_views',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
