# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-11-17 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_tool', '0009_auto_20171116_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='views',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
