# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_tool', '0010_keyword_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['pk']},
        ),
    ]
