# Generated by Django 2.2.4 on 2020-02-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatsonTranscript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_id', models.CharField(max_length=50, unique=True)),
                ('video_id_hash', models.BigIntegerField(db_index=True, default=0)),
                ('transcript', models.TextField(blank=True, default=None, null=True)),
                ('submitted', models.DateTimeField(blank=True, default=None, null=True)),
                ('retrieved', models.DateTimeField(blank=True, default=None, null=True)),
                ('job_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
