# Generated by Django 2.2.4 on 2020-01-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqtranscript',
            name='job_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
