# Generated by Django 2.2.4 on 2020-02-08 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0052_auto_20200207_2147'),
        ('transcripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watsontranscript',
            name='language',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcript_language', to='audit_tool.AuditLanguage'),
        ),
    ]
