# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-22 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=50, unique=True)),
                ('channel_id', models.CharField(max_length=50)),
                ('channel_title', models.CharField(max_length=225)),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('scanned', models.BooleanField(default=False)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='related_tool.RelatedVideo')),
            ],
        ),
    ]
