# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-22 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('related_tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedvideo',
            name='scanned',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
