# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-18 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist_video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistvideo',
            name='source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blacklist_video.BlacklistVideo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blacklistvideo',
            name='video_id',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
