# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-18 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist_video', '0002_auto_20190318_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistvideo',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blacklist_video.BlacklistVideo'),
        ),
    ]
