# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-10-18 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20171018_0643'),
        ('userprofile', '0003_userprofile_is_subscribed'),
    ]

    operations = [
    ]
