# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-10-18 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20171018_0911'),
        ('userprofile', '0003_auto_20171018_0643'),
    ]

    operations = [
    ]
