# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-11-10 09:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20171023_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_access_media_buying',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='permissions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'channel': {'audience': False, 'details': False, 'filter': False, 'list': False}, 'keyword': {'details': False, 'list': False}, 'segment': {'channel': {'all': False, 'private': False}, 'keyword': {'all': False, 'private': False}, 'video': {'all': False, 'private': False}}, 'settings': {'billing': True, 'my_aw_accounts': False, 'my_yt_channels': True}, 'video': {'audience': False, 'details': False, 'filter': False, 'list': False}, 'view': {'benchmarks': False, 'create_and_manage_campaigns': False, 'highlights': False, 'performance': False, 'trends': False}}),
        ),
    ]
