# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-11-13 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20171110_0928'),
        ('userprofile', '0003_userprofile_is_subscribed'),
    ]

    operations = [
    ]
