# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-11-18 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_plan_payments_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pre_backed_segments',
            field=models.BooleanField(default=False),
        ),
    ]
