# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-11-18 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_userprofile_pre_backed_segments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='pre_backed_segments',
            new_name='pre_baked_segments',
        ),
    ]
