# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-11-21 13:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_event'),
        ('userprofile', '0011_plan_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payments_subscription', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.Subscription')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
