# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-11-22 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
