# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-12-11 14:54
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_plan_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pre_baked_segments',
        ),
        migrations.AddField(
            model_name='plan',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='permissions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
