# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-12-21 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_auto_20171211_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='can_access_media_buying',
        ),
    ]
