# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-01-24 17:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0015_remove_userprofile_can_access_media_buying'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='permissions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
