# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-01-25 16:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0016_userprofile_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='access',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
