# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-02-23 11:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0017_userprofile_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='permissions',
        ),
        migrations.AddField(
            model_name='plan',
            name='access',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
