# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-04-10 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0018_auto_20180223_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_subscribed_to_campaign_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
