# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-04-25 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('userprofile', '0019_userprofile_is_subscribed_to_campaign_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPermission',
            fields=[
            ],
            options={
                'verbose_name': 'access_permission',
                'proxy': True,
            },
            bases=('auth.permission',),
        ),
    ]
