# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-04-22 21:51
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0019_userprofile_is_subscribed_to_campaign_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_set', models.CharField(blank=True, max_length=255, null=True)),
                ('permissions_values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
            ],
        ),
    ]
