# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-05-11 14:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0021_remove_plan_subsciption'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aw_settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
