# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-06-04 06:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0023_auto_20180515_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_influencer',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='aw_settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'dashboard_ad_words_rates': False, 'dashboard_campaigns_segmented': False, 'dashboard_costs_are_hidden': False, 'dashboard_remarketing_tab_is_hidden': False, 'demo_account_visible': False, 'global_account_visibility': False, 'hidden_campaign_types': {}, 'show_conversions': False, 'visible_accounts': []}),
        ),
    ]
