# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 15:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0035_fix_campaign_placement_links'),
        ('userprofile', '0024_auto_20180604_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='historical_aw_account',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_aw_historical', to='aw_reporting.AWConnectionToUserRelation'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='aw_settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=userprofile.models.get_default_settings),
        ),
    ]
