# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 15:01
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0035_fix_campaign_placement_links'),
        ('userprofile', '0025_lowercase_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='historical_aw_account',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_aw_historical', to='aw_reporting.AWConnectionToUserRelation'),
        ),
    ]
