# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-06-25 09:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations
from django.db.models.functions import Lower

import userprofile.models


def lowercase_email(apps, _):
    user_profile_model = apps.get_model("userprofile", "UserProfile")
    user_profile_model.objects.all().update(email=Lower("email"))


class Migration(migrations.Migration):
    dependencies = [
        ('userprofile', '0024_auto_20180604_0641'),
    ]

    operations = [
        migrations.RunPython(lowercase_email),
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('objects', userprofile.models.UserProfileManager()),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='aw_settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=userprofile.models.get_default_settings),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=userprofile.models.LowercaseEmailField(
                max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
