# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 09:11
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('userprofile', '0025_user_historical_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='historical_aw_account',
            field=models.ForeignKey(
                default=None, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='user_aw_historical',
                to='aw_reporting.AWConnectionToUserRelation'),
        ),
    ]
