# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0025_user_historical_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_registered_via_google',
            field=models.NullBooleanField(default=None),
        ),
    ]
