# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0026_userprofile_google_account_id'),
        ('userprofile', '0026_alter_historical_link_on_delete_set_null'),
    ]

    operations = [
    ]
