# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-03 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0028_userprofile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='annual_ad_spend',
            field=models.CharField(blank=True, choices=[(userprofile.models.AnnualAdSpend('$0-$100K'), '$0-$100K'), (userprofile.models.AnnualAdSpend('$100K-$250K'), '$100K-$250K'), (userprofile.models.AnnualAdSpend('$250k+'), '$250k+')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[(userprofile.models.UserType('creator'), 'creator'), (userprofile.models.UserType('brand'), 'brand')], max_length=255, null=True),
        ),
    ]
