# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-03 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0028_userprofile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='annual_ad_spend',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
