# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-12 10:46
from __future__ import unicode_literals

from django.db import migrations

# Deprecated permissions data migration in release/5.12


class Migration(migrations.Migration):
    dependencies = [
        ('userprofile', '0029_add_new_fields_type_annual_spend_subscribe'),
    ]

