# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-12 10:46
from __future__ import unicode_literals

from django.core.management import call_command
from django.db import migrations


def make_groups_and_accesses_data_migration(*args, **kwargs):
    call_command("upgrade_groups_and_user_permissions")


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0029_add_new_fields_type_annual_spend_subscribe'),
    ]

    operations = [
        migrations.RunPython(make_groups_and_accesses_data_migration)
    ]
