# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-17 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0030_auto_20181012_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='historical_aw_account',
        ),
    ]
