# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-18 09:21
from __future__ import unicode_literals

from django.apps import apps
from django.contrib.contenttypes.management import create_contenttypes
from django.core.management import call_command
from django.db import migrations


def sync_permissions(*_):
    create_contenttypes(apps.get_app_config("userprofile"))
    call_command("upgrade_groups_and_user_permissions")


class Migration(migrations.Migration):
    dependencies = [
        ('userprofile', '0031_remove_userprofile_historical_aw_account'),
    ]

    operations = [
        migrations.RunPython(sync_permissions)
    ]
