# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-18 09:21
from __future__ import unicode_literals

from django.apps import apps
from django.contrib.contenttypes.management import create_contenttypes
from django.db import migrations

from userprofile.permissions import Permissions


def sync_permissions(apps_config, *_):
    create_contenttypes(apps.get_app_config("userprofile"))
    Permissions.sync_groups(apps_config)


class Migration(migrations.Migration):
    dependencies = [
        ('userprofile', '0031_remove_userprofile_historical_aw_account'),
    ]

    operations = [
        migrations.RunPython(sync_permissions)
    ]
