# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-22 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0032_update_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='synced_with_email_campaign',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
