# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-15 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0034_remove_userprofile_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
