# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-15 13:30
from __future__ import unicode_literals

from django.db import migrations

from userprofile.models import UserStatuses


def update_status(apps, schema_editor):
    user_profile_model = apps.get_model("userprofile", "UserProfile")
    user_profile_model.objects.all().update(status=UserStatuses.active)


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0035_userprofile_status"),
    ]

    operations = [
        migrations.RunPython(update_status),
    ]
