# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-29 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0036_auto_20181115_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_accepted_GDPR',
            field=models.BooleanField(default=False),
        ),
    ]
