# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-31 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    def set_userprofiles_GDPR_null(apps, schema_editor):
        UserTable = apps.get_model('userprofile', 'UserProfile')
        UserTable.objects.all().update(has_accepted_GDPR=None)

    dependencies = [
        ('userprofile', '0037_userprofile_has_accepted_gdpr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='has_accepted_GDPR',
            field=models.NullBooleanField(default=None),
        ),
        migrations.RunPython(set_userprofiles_GDPR_null)
    ]
