# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-24 09:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations

DEMO_ACCOUNT_ID = "demo"


def update_demo_account_visibility(apps, schema_editor):
    userprofile_model = apps.get_model("userprofile", "UserProfile")
    for userprofile in userprofile_model.objects.all():
        settings = userprofile.aw_settings
        if settings["demo_account_visible"]:
            settings["visible_accounts"] = [DEMO_ACCOUNT_ID] + settings["visible_accounts"]
        del settings["demo_account_visible"]
        userprofile.save()


class Migration(migrations.Migration):
    dependencies = [
        ("userprofile", "0038_auto_20190131_1822"),
    ]

    operations = [
        migrations.RunPython(update_demo_account_visibility),
        migrations.AlterField(
            model_name="userprofile",
            name="aw_settings",
            field=django.contrib.postgres.fields.jsonb.JSONField(default={
                "dashboard_ad_words_rates": False,
                "dashboard_campaigns_segmented": False,
                "dashboard_costs_are_hidden": False,
                "dashboard_remarketing_tab_is_hidden": False,
                "global_account_visibility": False,
                "hidden_campaign_types": {},
                "show_conversions": False,
                "visible_accounts": [DEMO_ACCOUNT_ID],
                "visible_all_accounts": False,
            }),
        ),
    ]
