# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-28 19:38
from __future__ import unicode_literals

from django.db import migrations


def add_brand_safety_group_to_users(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    brand_safety_group = Group.objects.filter(name="Brand Safety Scoring")
    if brand_safety_group.exists():
        brand_safety_group = brand_safety_group.first()
        UserProfile = apps.get_model("userprofile", "UserProfile")
        for user in UserProfile.objects.all():
            user.groups.add(brand_safety_group)


def remove_brand_safety_group_from_users(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    brand_safety_group = Group.objects.filter(name="Brand Safety Scoring")
    if brand_safety_group.exists():
        brand_safety_group = brand_safety_group.first()
        UserProfile = apps.get_model("userprofile", "UserProfile")
        for user in UserProfile.objects.all():
            user.groups.remove(brand_safety_group)


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0040_auto_20190516_1912'),
    ]

    operations = [
        migrations.RunPython(add_brand_safety_group_to_users, remove_brand_safety_group_from_users),
    ]
