# Generated by Django 2.2.4 on 2020-02-04 15:05

from django.db import migrations

from aw_reporting.demo.data import DEMO_ACCOUNT_ID


def map_id(old_id):
    return DEMO_ACCOUNT_ID if old_id == 'demo' else int(old_id)


def map_settings(apps, schema_editor):
    user_model = apps.get_model('userprofile.UserProfile')
    for user in user_model.objects.all():
        aw_settings = dict(**user.aw_settings)
        aw_settings['visible_accounts'] = [map_id(old_id) for old_id in aw_settings['visible_accounts']]
        user.aw_settings = aw_settings
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('userprofile', '0043_userdevicetoken'),
    ]

    operations = [
        migrations.RunPython(map_settings),
    ]
