# Generated by Django 2.2.4 on 2020-03-04 19:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
from userprofile.constants import DEFAULT_DOMAIN


def create_defaults(apps, schema_editor):
    WhiteLabel = apps.get_model("userprofile", "WhiteLabel")
    WhiteLabel.objects.create(domain=DEFAULT_DOMAIN)


def revert(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0044_aw_settings_alter_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('config', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
        migrations.RunPython(create_defaults, reverse_code=revert)
    ]
