# Generated by Django 2.2.4 on 2020-03-18 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0045_whitelabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.WhiteLabel'),
        ),
    ]
