# Generated by Django 3.0.4 on 2020-07-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw_reporting', '0096_opportunity_currency_code'),
        ('userprofile', '0047_domain_datamigration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='opportunities',
            field=models.ManyToManyField(db_index=True, to='aw_reporting.Opportunity'),
        ),
    ]
