# Generated by Django 3.0.4 on 2021-01-13 00:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0047_domain_datamigration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=128, unique=True)),
                ('default_value', models.BooleanField(db_index=True, default=False)),
                ('display', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='perms',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
