# Generated by Django 3.1.6 on 2021-02-02 10:34

from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0048_auto_20210113_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='aw_settings',
            field=models.JSONField(default=userprofile.models.get_default_settings),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='has_accepted_GDPR',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='perms',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='whitelabel',
            name='config',
            field=models.JSONField(default=dict),
        ),
    ]
