# Generated by Django 3.1.6 on 2021-02-09 22:42

from django.db import migrations

from userprofile.models import WhiteLabel


def update_items(apps, *_, **__):
    """ Remove legacy permissions from domain access and keep the domains permissions mappings untouched """
    all_white_labels = WhiteLabel.objects.all()
    for white_label in all_white_labels:
        if (isinstance(white_label.config, dict) and
                'disable' in white_label.config and
                isinstance(white_label.config['disable'], list) and
                len(white_label.config['disable']) > 0):
            updated = False
            if ('Research > Channels' in white_label.config['disable'] or
                'Research > Videos' in white_label.config['disable']):
                white_label.config['disable'].append('Research')
                updated = True
                if 'Research > Channels' in white_label.config['disable']:
                    white_label.config['disable'].remove('Research > Channels')
                if 'Research > Videos' in white_label.config['disable']:
                    white_label.config['disable'].remove('Research > Videos')
            if ('Media Planning > Brand Suitable Target Lists' in white_label.config['disable'] or
                'Media Planning > Custom Target Lists' in white_label.config['disable']):
                white_label.config['disable'].append('List Builder')
                updated = True
                if 'Media Planning > Brand Suitable Target Lists' in white_label.config['disable']:
                    white_label.config['disable'].remove('Media Planning > Brand Suitable Target Lists')
                if 'Media Planning > Custom Target Lists' in white_label.config['disable']:
                    white_label.config['disable'].remove('Media Planning > Custom Target Lists')
            if 'Research > Keywords' in white_label.config['disable']:
                white_label.config['disable'].remove('Research > Keywords')
                updated = True
            if 'Tools > Health Check Tool' in white_label.config['disable']:
                white_label.config['disable'].remove('Tools > Health Check Tool')
                updated = True
            if updated:
                white_label.save()


def do_nothing(*_, **__):
    """ Required for reverse migration """
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('userprofile', '0051_auto_20210209_1709'),
    ]

    operations = [
        migrations.RunPython(update_items, reverse_code=do_nothing)
    ]
