# Generated by Django 3.1.6 on 2021-03-02 18:25

from django.db import migrations

REVIEW = "Review"
DISABLE = "disable"

def set_default_performiq_permission(apps, schema_editor):
    WhiteLabel = apps.get_model("userprofile", "WhiteLabel")
    for white_label in WhiteLabel.objects.all():
        config = white_label.config
        disable = config.get(DISABLE, [])

        if white_label.domain.lower() == "viewiq":
            try:
                disable.remove(REVIEW)
            except ValueError:
                pass
        else:
            disable.append(REVIEW)

        disable = list(set(disable))
        config[DISABLE] = disable
        white_label.config = config
        white_label.save(update_fields=["config"])


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0052_update_white_label_domain_permissions'),
    ]

    operations = [
        migrations.RunPython(set_default_performiq_permission)
    ]
