# Generated by Django 3.1.6 on 2021-03-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0053_performiq_disabled_by_default_except_for_viewiq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalPermission',
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.JSONField(default=dict),
        ),
    ]
