# Generated by Django 3.1.7 on 2021-03-08 21:47

from django.db import migrations

from userprofile.models import UserProfile
from userprofile.constants import UserSettingsKey
from aw_reporting.demo.data import DEMO_ACCOUNT_ID


def add_demo_account_to_all_users(apps, schema_editor):
    """
    for each user, we'll make sure that it has the DEMO_ACCOUNT_ID listed in the setting:
    "aw_settings[UserSettingsKey.VISIBLE_ACCOUNTS]"
    """
    for user in UserProfile.objects.all():
        if user.aw_settings:
            update_user = False
            if UserSettingsKey.VISIBLE_ACCOUNTS in user.aw_settings and \
               isinstance(user.aw_settings[UserSettingsKey.VISIBLE_ACCOUNTS], list) and \
               not DEMO_ACCOUNT_ID in user.aw_settings[UserSettingsKey.VISIBLE_ACCOUNTS]:
                user.aw_settings[UserSettingsKey.VISIBLE_ACCOUNTS].insert(0, DEMO_ACCOUNT_ID)
                update_user = True
            if UserSettingsKey.HIDDEN_CAMPAIGN_TYPES in user.aw_settings and \
               isinstance(user.aw_settings[UserSettingsKey.HIDDEN_CAMPAIGN_TYPES], dict) and \
               DEMO_ACCOUNT_ID in user.aw_settings[UserSettingsKey.HIDDEN_CAMPAIGN_TYPES].keys():
                user.aw_settings[UserSettingsKey.HIDDEN_CAMPAIGN_TYPES].pop(DEMO_ACCOUNT_ID)
                update_user = True
            if update_user:
                user.save(update_fields=["aw_settings"])


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0055_auto_20210306_0057'),
    ]

    operations = [
        migrations.RunPython(add_demo_account_to_all_users),
    ]
