# Generated by Django 3.1.6 on 2021-03-13 00:21

from django.db import migrations


BUILD__CTL_VET_ADMIN = "build.ctl_vet_admin"


def remove_vet_admin_permission(apps, schema_editor):
    """
    remove the "build.ctl_vet_admin" permission
    :param apps:
    :param schema_editor:
    :return:
    """
    UserProfile = apps.get("userprofile", "UserProfile")
    for user in UserProfile.objects.all():
        vet_admin_perm = user.perms.pop(BUILD__CTL_VET_ADMIN, None)
        if vet_admin_perm is None:
            continue

        user.save(update_fields=["perms"])


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0055_auto_20210306_0057'),
    ]

    operations = [
        migrations.RunPython(remove_vet_admin_permission)
    ]
