# Generated by Django 3.1.7 on 2021-03-17 19:09

from django.db import migrations

base_perm = "blocklist_manager"
actions = (".create", ".delete", ".export",)

def update_blocklist_manager_perms(apps, schema_editor):
    UserProfile = apps.get_model("userprofile", "UserProfile")
    for user in UserProfile.objects.all():

        # no need to add new permissions for admin users since they have access by default
        if user.is_staff:
            continue

        # enable new video and channel perms if user already had access
        for action in actions:
            try:
                user_has_perm = user.has_permission(base_perm + action)
            except:
                user_has_perm = False

            if user_has_perm:
                user.perms[base_perm + action + "_video"] = True
                user.perms[base_perm + action + "_channel"] = True
            else:
                user.perms[base_perm + action + "_video"] = False
                user.perms[base_perm + action + "_channel"] = False

            # remove old permission
            user.perms.pop(base_perm + action, None)

        user.save(updated_fields=["perms"])


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0056_remove_vet_admin_permission'),
    ]

    operations = [
        migrations.RunPython(update_blocklist_manager_perms),
    ]
