# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-14 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.CharField(db_index=True, max_length=255)),
                ('videos', models.BigIntegerField()),
                ('impressions', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_id', models.CharField(db_index=True, max_length=30)),
                ('video_title', models.CharField(max_length=255)),
                ('channel_id', models.CharField(max_length=30)),
                ('channel_title', models.CharField(max_length=255)),
                ('preferred', models.BooleanField()),
                ('impressions', models.BigIntegerField()),
                ('hits', models.BigIntegerField()),
                ('words', models.TextField()),
                ('account_info', models.TextField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='videoaudit',
            unique_together=set([('date', 'video_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='keywordaudit',
            unique_together=set([('date', 'keyword')]),
        ),
    ]
