# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-22 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoaudit',
            name='sentiment',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='videoaudit',
            name='channel_title',
            field=models.CharField(default='No title', max_length=255),
        ),
    ]
