# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-05 22:19
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('segment', '0026_auto_20190304_1633'),
        ('audit_tool', '0004_videoauditignore'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIScriptTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('cursor', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TopicAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('is_running', models.BooleanField(db_index=True, default=True)),
                ('from_beginning', models.BooleanField(default=False)),
                ('completed_at', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='keyword',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords',
                                    to='audit_tool.TopicAudit'),
        ),
        migrations.AlterIndexTogether(
            name='topicaudit',
            index_together=set([('is_running', 'from_beginning')]),
        ),
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together=set([('keyword', 'topic')]),
        ),
    ]
