# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-05 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0026_auto_20190304_1633'),
        ('audit_tool', '0004_videoauditignore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TopicAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('is_running', models.NullBooleanField(db_index=True, default=None)),
                ('from_beginning', models.NullBooleanField(default=None)),
                ('completed_at', models.DateField(blank=True, default=None, null=True)),
                ('channel_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_topic', to='segment.PersistentSegmentChannel')),
                ('video_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_topic', to='segment.PersistentSegmentVideo')),
            ],
        ),
        migrations.AddField(
            model_name='keyword',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='audit_tool.TopicAudit'),
        ),
        migrations.AlterIndexTogether(
            name='topicaudit',
            index_together=set([('is_running', 'from_beginning')]),
        ),
    ]
