# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-05 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0026_auto_20190304_1633'),
        ('audit_tool', '0004_videoauditignore'),
    ]
operations = [
    migrations.CreateModel(
        name='TopicAudit',
        fields=[
            ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('date', models.DateField(db_index=True)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('title', models.CharField(max_length=255)),
            ('is_running', models.NullBooleanField(default=None)),
            ('from_beginning', models.NullBooleanField(default=None)),
            ('completed_at', models.DateField(blank=True, default=None, null=True)),
            ('keywords', models.TextField()),
            ('channel_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_topic', to='segment.PersistentSegmentChannel')),
            ('video_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_topic', to='segment.PersistentSegmentVideo')),
        ],
        options={
            'abstract': False,
        },
    ),
]
