# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-06 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0005_auto_20190305_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicaudit',
            name='start_cursor',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topicaudit',
            name='completed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
