# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-11 21:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0006_auto_20190306_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('parent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('video_id', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField()),
                ('like_count', models.IntegerField(blank=True, null=True)),
                ('is_top_level', models.BooleanField(default=True)),
                ('reply_count', models.IntegerField(blank=True, null=True)),
                ('time_stamp', models.CharField(default='', max_length=255)),
                ('found_items', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('thumbnail_image_url', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='audit_tool.YoutubeUser'),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([('id', 'video_id')]),
        ),
    ]
