# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-11 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0007_auto_20190311_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_top_level',
        ),
    ]
