# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-12 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0008_remove_comment_is_top_level'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='YoutubeUser',
        ),
    ]
