# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-12 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0012_auto_20190411_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcategory',
            name='category_display',
            field=models.TextField(default=None, null=True),
        ),
    ]
