# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-15 23:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0014_auto_20190415_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditvideoprocessor',
            name='word_hits',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True),
        ),
    ]
