# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-25 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0015_auditvideoprocessor_word_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiscripttracker',
            name='cursor_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
