# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-23 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0015_auditvideoprocessor_word_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditprocessor',
            name='pause',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
