# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-23 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0016_auditprocessor_pause'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditchannelmeta',
            name='view_count',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
