# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-25 23:04
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('audit_tool', '0020_apiscripttracker_cursor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditchannelmeta',
            name='default_language',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='ac_default_language', to='audit_tool.AuditLanguage'),
        ),
        migrations.AlterField(
            model_name='auditchannelmeta',
            name='language',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='ac_language', to='audit_tool.AuditLanguage'),
        ),
    ]
