# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-20 19:48
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('audit_tool', '0023_auditchannelmeta_video_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditExporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('clean', models.NullBooleanField(db_index=True, default=None)),
                ('completed', models.DateTimeField(db_index=True, default=None, null=True)),
                ('file_name', models.TextField(default=None, null=True)),
                ('final', models.BooleanField(db_index=True, default=False)),
                ('audit',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit_tool.AuditProcessor')),
            ],
        ),
    ]
