# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-27 19:11
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('audit_tool', '0025_auditexporter_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditchannelmeta',
            name='last_uploaded',
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
    ]
