# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-11 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0026_auditchannelmeta_last_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditprocessor',
            name='name',
            field=models.CharField(db_index=True, default=None, max_length=255, null=True),
        ),
    ]
