# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-15 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0028_auto_20190715_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditchannelmeta',
            name='last_uploaded_view_count',
            field=models.BigIntegerField(db_index=True, default=None, null=True),
        ),
    ]
