# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-02 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0030_auditchannelmeta_last_uploaded_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditvideometa',
            name='default_audio_language',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='audit_tool.AuditLanguage'),
        ),
        migrations.AddField(
            model_name='auditvideometa',
            name='duration',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='auditvideometa',
            name='language',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='av_language', to='audit_tool.AuditLanguage'),
        ),
    ]
