# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-16 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('audit_tool', '0031_auto_20190802_1757'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='topic',
        ),
        migrations.AlterIndexTogether(
            name='topicaudit',
            index_together=set([]),
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
        migrations.DeleteModel(
            name='TopicAudit',
        ),
    ]
