# Generated by Django 2.2.4 on 2019-08-23 11:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0032_auto_20190816_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditchannelprocessor',
            name='word_hits',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='auditprocessor',
            name='cached_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='auditprocessor',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='auditvideoprocessor',
            name='word_hits',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='blacklistitem',
            name='blacklist_category',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='comment',
            name='found_items',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
