# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-10 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0033_fix_default_value_for_json_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditProcessorCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('count', models.BigIntegerField(db_index=True, default=0)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit_tool.AuditProcessor')),
            ],
        ),
    ]
