# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-23 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0034_auditprocessorcache'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditVideoTranscript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.TextField(default=None, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit_tool.AuditVideo')),
            ],
        ),
    ]
