# Generated by Django 2.2.4 on 2019-10-24 18:04

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('audit_tool', '0037_auto_20191018_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditexporter',
            name='started',
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
    ]
