# Generated by Django 2.2.4 on 2019-10-24 19:31

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('audit_tool', '0038_auditexporter_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditexporter',
            name='percent_done',
            field=models.IntegerField(default=0),
        ),
    ]
