# Generated by Django 2.2.4 on 2019-11-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0039_auditexporter_percent_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditprocessor',
            name='temp_stop',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
