# Generated by Django 2.2.4 on 2019-11-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0040_auditprocessor_temp_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditprocessor',
            name='source',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
