# Generated by Django 2.2.4 on 2019-11-15 18:11

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('audit_tool', '0041_auditprocessor_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditchannel',
            name='processed_time',
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
    ]
