# Generated by Django 2.2.4 on 2019-11-26 18:41

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('audit_tool', '0044_auditexporter_export_as_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditchannelmeta',
            name='monetised',
            field=models.NullBooleanField(default=None),
        ),
    ]
