# Generated by Django 2.2.4 on 2020-01-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0048_auditvideometa_age_restricted'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditvideo',
            name='processed_time',
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
    ]
