# Generated by Django 2.2.4 on 2020-02-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0049_auditvideo_processed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditvideometa',
            name='made_for_kids',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
    ]
