# Generated by Django 2.2.4 on 2020-02-08 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0049_auditvideo_processed_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditChannelVet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_checked_out', models.BooleanField(db_index=True, default=False)),
                ('processed', models.DateTimeField(db_index=True, default=None, null=True)),
                ('processed_by_user_id', models.IntegerField(db_index=True, default=None, null=True)),
                ('skipped', models.NullBooleanField(db_index=True, default=None)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit_tool.AuditProcessor')),
                ('channel', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vets', to='audit_tool.AuditChannel')),
            ],
            options={
                'unique_together': {('audit', 'channel')},
            },
        ),
    ]
