# Generated by Django 2.2.4 on 2020-02-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0050_auditchannelvet'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditchannelvet',
            name='checked_out_at',
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
    ]
