# Generated by Django 2.2.4 on 2020-02-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0051_auto_20200207_2124'),
    ]

    run_before = [
        ('transcripts', '0001_initial')
    ]

    operations = [
        migrations.AlterField(
            model_name='auditexporter',
            name='machine',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditexporter',
            name='thread',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
