# Generated by Django 2.2.4 on 2020-02-11 19:53

from django.db import migrations, models
import django.db.models.deletion


AGE_GROUP_CHOICES = [
    # id, age_group, parent_id
    (0, "0 - 3 Toddlers", None),
    (1, "4 - 8 Young Kids", None),
    (2, "9 - 12 Older Kids", None),
    (3, "13 - 17 Teens", None),
    (4, "18 - 35 Adults", None),
    (5, "36 - 54 Older Adults", None),
    (6, "55+ Seniors", None),
    (7, "Group - Kids (not teens)", 2),  # parent=2
    (8, "Group - Family Friendly", 3),  # parent=3
]
GENDER_CHOICES = [
    (0, "Neutral"),
    (1, "Female"),
    (2, "Male"),
]
CHANNEL_TYPE_CHOICES = [
    (0, "MC / Brand"),
    (1, "Regular UGC"),
    (2, "Premium UGC"),
]


def create_items(apps, schema_editor):
    AuditAgeGroup = apps.get_model("audit_tool", "AuditAgeGroup")
    AuditGender = apps.get_model("audit_tool", "AuditGender")
    AuditChannelType = apps.get_model("audit_tool", "AuditChannelType")

    for id, age_group, parent_id in AGE_GROUP_CHOICES:
        AuditAgeGroup.objects.create(id=id, age_group=age_group, parent_id=parent_id)

    for id, gender in GENDER_CHOICES:
        AuditGender.objects.create(id=id, gender=gender)

    for id, channel_type in CHANNEL_TYPE_CHOICES:
        AuditChannelType.objects.create(id=id, channel_type=channel_type)


def delete_items(apps, schema_editor):
    """
    Required for reverse migration
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0052_auto_20200207_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditChannelType',
            fields=[
                ('id', models.IntegerField(choices=[(0, 'MC / Brand'), (1, 'Regular UGC'), (2, 'Premium UGC')], primary_key=True, serialize=False)),
                ('channel_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AuditGender',
            fields=[
                ('id', models.IntegerField(choices=[(0, 'Neutral'), (1, 'Female'), (2, 'Male')], primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='AuditAgeGroup',
            fields=[
                ('id', models.IntegerField(choices=[(0, '0 - 3 Toddlers'), (1, '4 - 8 Young Kids'), (2, '9 - 12 Older Kids'), (3, '13 - 17 Teens'), (4, '18 - 35 Adults'), (5, '36 - 54 Older Adults'), (6, '55+ Seniors'), (7, 'Group - Kids (not teens)'), (8, 'Group - Family Friendly')], primary_key=True, serialize=False)),
                ('age_group', models.CharField(max_length=25)),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='audit_tool.AuditAgeGroup')),
            ],
        ),
        migrations.CreateModel(
            name='AuditChannelVet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean', models.NullBooleanField(db_index=True, default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_out_at', models.DateTimeField(db_index=True, default=None, null=True)),
                ('processed', models.DateTimeField(db_index=True, default=None, null=True)),
                ('processed_by_user_id', models.IntegerField(db_index=True, default=None, null=True)),
                ('skipped', models.NullBooleanField(db_index=True, default=None)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit_tool.AuditProcessor')),
                ('channel', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vets', to='audit_tool.AuditChannel')),
            ],
            options={
                'unique_together': {('audit', 'channel')},
            },
        ),
        migrations.RunPython(create_items, reverse_code=delete_items)
    ]
