# Generated by Django 2.2.4 on 2020-02-11 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0053_auditagegroup_auditchanneltype_auditchannelvet_auditgender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuditChannelType',
            new_name='AuditContentType',
        ),
        migrations.RenameField(
            model_name='auditcontenttype',
            old_name='channel_type',
            new_name='content_type',
        ),
        migrations.CreateModel(
            name='AuditVideoVet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean', models.NullBooleanField(db_index=True, default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_out_at', models.DateTimeField(db_index=True, default=None, null=True)),
                ('processed', models.DateTimeField(db_index=True, default=None, null=True)),
                ('processed_by_user_id', models.IntegerField(db_index=True, default=None, null=True)),
                ('skipped', models.NullBooleanField(db_index=True, default=None)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit_tool.AuditProcessor')),
                ('video', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_vets', to='audit_tool.AuditVideo')),
            ],
            options={
                'unique_together': {('audit', 'video')},
            },
        ),
    ]
