# Generated by Django 2.2.4 on 2020-02-18 21:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('audit_tool', '0054_auto_20200211_2348'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='auditchannelprocessor',
            index_together={('audit', 'processed')},
        ),
        migrations.AlterIndexTogether(
            name='auditvideoprocessor',
            index_together={('audit', 'processed')},
        ),
    ]
