# Generated by Django 2.2.4 on 2020-02-19 20:58

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('audit_tool', '0055_auto_20200218_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditvideotranscript',
            name='job_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auditvideotranscript',
            name='job_id_hash',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='auditvideotranscript',
            name='retrieved',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='auditvideotranscript',
            name='source',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='auditvideotranscript',
            name='submitted',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
