# Generated by Django 2.2.4 on 2020-03-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0058_auto_20200302_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditexporter',
            name='export_as_channels',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='auditexporter',
            name='export_as_keywords',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='auditexporter',
            name='export_as_videos',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
