# Generated by Django 3.0.4 on 2020-06-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0061_auditchannelmeta_hidden_subscriber_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditchannelprocessor',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='auditvideoprocessor',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
