# Generated by Django 3.0.4 on 2020-06-25 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0062_alter_pk_bigint'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditchannelmeta',
            name='primary_video_language',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ac_video_language', to='audit_tool.AuditLanguage'),
        ),
    ]
