# Generated by Django 3.0.4 on 2020-06-24 19:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0062_alter_pk_bigint'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditchannelmeta',
            name='misc',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
    ]
