# Generated by Django 3.0.4 on 2020-07-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0063_auditchannelmeta_primary_video_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditvideometa',
            name='aspect_ratio',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='auditvideometa',
            name='live_broadcast',
            field=models.NullBooleanField(default=None),
        ),
    ]
