# Generated by Django 3.0.4 on 2020-07-02 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0064_auto_20200701_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditvideotranscript',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='auditvideotranscript',
            name='job_id_hash',
        ),
        migrations.RemoveField(
            model_name='auditvideotranscript',
            name='retrieved',
        ),
        migrations.RemoveField(
            model_name='auditvideotranscript',
            name='submitted',
        ),
    ]
