# Generated by Django 3.0.4 on 2020-07-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0065_auto_20200702_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditchannelmeta',
            name='dislikes',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='auditchannelmeta',
            name='likes',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
