# Generated by Django 3.0.4 on 2020-07-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0067_auditcontentquality'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_number', models.IntegerField(unique=True)),
                ('last_seen', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.AlterField(
            model_name='auditcontenttype',
            name='id',
            field=models.IntegerField(choices=[(0, 'UGC'), (1, 'Broadcast'), (2, 'Brands')], primary_key=True, serialize=False),
        ),
    ]
