# Generated by Django 3.0.4 on 2020-08-11 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0068_auto_20200729_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditchannelvet',
            name='audit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='audit_tool.AuditProcessor'),
        ),
        migrations.AlterField(
            model_name='auditvideovet',
            name='audit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='audit_tool.AuditProcessor'),
        ),
    ]
