# Generated by Django 3.0.4 on 2020-09-01 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0069_auto_20200811_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='IASChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ias_verified', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='audit_tool.AuditChannel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
