# Generated by Django 3.0.4 on 2020-09-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0070_iaschannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistitem',
            name='blocked_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='blacklistitem',
            name='processed_by_user_id',
            field=models.IntegerField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='blacklistitem',
            name='unblocked_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='blacklistitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
