# Generated by Django 3.0.4 on 2020-09-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0071_auto_20200902_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistitem',
            name='blocklist',
            field=models.BooleanField(db_index=True, default=True),
        )
    ]
