# Generated by Django 3.1.6 on 2021-02-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0075_auto_20201123_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditchannelmeta',
            name='monetised',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='auditchannelmeta',
            name='synced_with_viewiq',
            field=models.BooleanField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditchannelprocessor',
            name='word_hits',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='auditchannelvet',
            name='clean',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='auditchannelvet',
            name='skipped',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='auditexporter',
            name='clean',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='auditprocessor',
            name='cached_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='auditprocessor',
            name='params',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='auditvideometa',
            name='age_restricted',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='auditvideometa',
            name='live_broadcast',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='auditvideometa',
            name='made_for_kids',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='auditvideoprocessor',
            name='word_hits',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='auditvideovet',
            name='clean',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='auditvideovet',
            name='skipped',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='blacklistitem',
            name='blacklist_category',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='comment',
            name='found_items',
            field=models.JSONField(default=dict),
        ),
    ]
