# Generated by Django 3.0.4 on 2021-01-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0075_auto_20201123_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditchannelmeta',
            name='name',
            field=models.TextField(default=None, null=True),
        ),
    ]
