# Generated by Django 3.1.6 on 2021-02-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0077_auto_20210202_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiscripttracker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='apiscripttracker',
            name='timestamp',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='apiscripttracker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
