# Generated by Django 3.1.7 on 2021-04-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_tool', '0078_auto_20210217_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditexporter',
            name='current_step',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='auditexporter',
            name='last_error',
            field=models.TextField(default=None, null=True),
        ),
    ]
