# Generated by Django 3.1.6 on 2021-03-26 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
        ('performiq', '0017_auto_20210318_2120')
    ]

    operations = [
        migrations.CreateModel(
            name='InsertionOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('display_name', models.CharField(default='', max_length=250)),
                ('update_time', models.DateTimeField(default=None, null=True)),
                ('entity_status', models.SmallIntegerField(choices=[(0, 'Unspecified'), (1, 'Active'), (2, 'Archived'), (3, 'Draft'), (4, 'Paused'), (5, 'Scheduled for Deletion')], db_index=True, default=None, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insertion_orders', to='oauth.campaign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('oauth_type', models.IntegerField(choices=[(0, 'Google Ads Oauth'), (1, 'Google DV360 Oauth')], db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=256, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_groups', to='oauth.campaign')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
