# Generated by Django 3.1.6 on 2021-03-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_adgroup_insertionorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
