# Generated by Django 3.1.6 on 2021-04-08 15:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthaccount',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='oauthaccount',
            name='viq_key',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='adgroup',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adgroups', to='oauth.campaign'),
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('display_name', models.CharField(default='', max_length=250)),
                ('update_time', models.DateTimeField(default=None, null=True)),
                ('entity_status', models.SmallIntegerField(choices=[(0, 'Unspecified'), (1, 'Active'), (2, 'Archived'), (3, 'Draft'), (4, 'Paused'), (5, 'Scheduled for Deletion')], db_index=True, default=None, null=True)),
                ('insertion_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='oauth.insertionorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='adgroup',
            name='line_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adgroups', to='oauth.lineitem'),
        ),
    ]
