# Generated by Django 3.1.6 on 2021-04-07 17:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_account_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthAccountData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.UUIDField(default=uuid.uuid4)),
                ('data', models.JSONField(default=dict)),
                ('oauth_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='oauth.oauthaccount')),
            ],
        ),
    ]
