# Generated by Django 3.1.7 on 2021-04-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0005_auto_20210413_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='adgroup',
            name='display_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='entity_status',
            field=models.SmallIntegerField(choices=[(0, 'Unspecified'), (1, 'Active'), (2, 'Archived'), (3, 'Draft'), (4, 'Paused'), (5, 'Scheduled for Deletion')], db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='update_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='oauthaccount',
            name='can_manage_clients',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
