# Generated by Django 3.0.4 on 2020-08-28 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('oauth_type', models.IntegerField(choices=[(0, 'Google Ads Oauth'), (1, 'Google DV360 Oauth')], db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, null=True)),
                ('token', models.CharField(max_length=150, null=True)),
                ('refresh_token', models.CharField(max_length=150, null=True)),
                ('revoked_access', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('oauth_type', models.IntegerField(choices=[(0, 'Google Ads Oauth'), (1, 'Google DV360 Oauth')], db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, null=True)),
                ('impressions', models.IntegerField(db_index=True, default=0)),
                ('video_views', models.IntegerField(db_index=True, default=0)),
                ('cost', models.FloatField(db_index=True, default=0)),
                ('cpm', models.FloatField(db_index=True, default=0)),
                ('cpv', models.FloatField(db_index=True, default=0)),
                ('ctr', models.FloatField(db_index=True, default=0)),
                ('active_view_viewability', models.FloatField(db_index=True, default=0)),
                ('video_quartile_100_rate', models.FloatField(db_index=True, default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performiq.OAuthAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
