# Generated by Django 3.0.4 on 2020-09-21 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performiq', '0003_auto_20200909_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='DV360Advertiser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('display_name', models.CharField(max_length=250)),
                ('update_time', models.DateTimeField()),
                ('entity_status', models.SmallIntegerField(choices=[(0, 'Unspecified'), (1, 'Active'), (2, 'Archived'), (3, 'Draft'), (4, 'Paused'), (5, 'Scheduled for Deletion')], db_index=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DV360Partner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('display_name', models.CharField(max_length=250)),
                ('update_time', models.DateTimeField()),
                ('entity_status', models.SmallIntegerField(choices=[(0, 'Unspecified'), (1, 'Active'), (2, 'Archived'), (3, 'Draft'), (4, 'Paused'), (5, 'Scheduled for Deletion')], db_index=True)),
                ('oauth_accounts', models.ManyToManyField(related_name='partners', to='performiq.OAuthAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DV360Campaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('display_name', models.CharField(max_length=250)),
                ('update_time', models.DateTimeField()),
                ('entity_status', models.SmallIntegerField(choices=[(0, 'Unspecified'), (1, 'Active'), (2, 'Archived'), (3, 'Draft'), (4, 'Paused'), (5, 'Scheduled for Deletion')], db_index=True)),
                ('advertiser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='performiq.DV360Advertiser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dv360advertiser',
            name='partner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisers', to='performiq.DV360Partner'),
        ),
    ]
