# Generated by Django 3.0.4 on 2020-09-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performiq', '0004_auto_20200921_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dv360partner',
            name='oauth_accounts',
            field=models.ManyToManyField(related_name='dv360_partners', to='performiq.OAuthAccount'),
        ),
    ]
