# Generated by Django 3.0.4 on 2020-09-23 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performiq', '0005_auto_20200922_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dv360advertiser',
            old_name='partner_id',
            new_name='partner',
        ),
        migrations.RenameField(
            model_name='dv360campaign',
            old_name='advertiser_id',
            new_name='advertiser',
        ),
    ]
