# Generated by Django 3.0.4 on 2020-09-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performiq', '0006_auto_20200923_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='dv360advertiser',
            name='oauth_accounts',
            field=models.ManyToManyField(related_name='dv360_advertisers', to='performiq.OAuthAccount'),
        ),
    ]
