# Generated by Django 3.0.4 on 2020-11-04 23:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performiq', '0008_auto_20201104_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='IQCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('results', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('started', models.DateTimeField(db_index=True, default=None, null=True)),
                ('completed', models.DateTimeField(db_index=True, default=None, null=True)),
                ('campaign', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='performiq.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='IQCampaignChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean', models.NullBooleanField(db_index=True, default=None)),
                ('meta_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('results', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('channel_id', models.CharField(db_index=True, max_length=128)),
                ('iq_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performiq.IQCampaign')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('oauth_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='performiq.OAuthAccount')),
            ],
        ),
        migrations.AlterField(
            model_name='campaign',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='performiq.Account'),
        ),
    ]
