# Generated by Django 3.0.4 on 2020-11-19 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performiq', '0009_auto_20201104_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='iqcampaign',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='iqcampaignchannel',
            name='iq_campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='performiq.IQCampaign'),
        ),
    ]
