# Generated by Django 3.0.4 on 2020-12-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performiq', '0010_auto_20201119_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthaccount',
            name='is_enabled',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
