# Generated by Django 3.0.4 on 2020-12-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performiq', '0011_oauthaccount_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='iqcampaign',
            name='name',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
