# Generated by Django 3.0.4 on 2020-12-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performiq', '0012_iqcampaign_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthaccount',
            name='is_syncing',
            field=models.BooleanField(default=False),
        ),
    ]
