# Generated by Django 3.0.4 on 2020-12-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performiq', '0012_iqcampaign_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthaccount',
            name='synced',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
