# Generated by Django 3.0.4 on 2021-01-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performiq', '0014_account_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='oauth_account',
        ),
        migrations.AddField(
            model_name='account',
            name='oauth_accounts',
            field=models.ManyToManyField(db_index=True, related_name='gads_accounts', to='performiq.OAuthAccount'),
        ),
    ]
