# Generated by Django 3.1.6 on 2021-03-18 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
        ('performiq', '0016_auto_20210202_1034'),
    ]

    operations = [
        # Removal of fields not required as we are renaming these tables
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='campaign',
                    name='account',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='campaign',
                    name='advertiser',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='dv360advertiser',
                    name='oauth_accounts',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='dv360advertiser',
                    name='partner',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='dv360partner',
                    name='oauth_accounts',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='oauthaccount',
                    name='user',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='iqcampaign',
                    name='campaign',
                    field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                            to='oauth.campaign'),
                ),
            ],
            database_operations=[],
        ),

        # Rename tables to oauth app
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Account',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Account',
                    table='oauth_account',
                )
            ]
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Campaign',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Campaign',
                    table='oauth_campaign',
                )
            ]
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='DV360Advertiser',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='DV360Advertiser',
                    table='oauth_dv360advertiser',
                )
            ]
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='DV360Partner',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='DV360Partner',
                    table='oauth_dv360partner',
                )
            ]
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='OAuthAccount',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='OAuthAccount',
                    table='oauth_oauthaccount',
                )
            ]
        ),
    ]
