# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-27 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authchannel',
            name='token_revocation',
            field=models.DateTimeField(null=True),
        ),
    ]
