# Generated by Django 3.0.4 on 2020-11-25 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_authchannel_token_revocation'),
    ]

    operations = [
    ]
