LANGUAGES = {
    "aa": "Afar",
    "ab": "Abkhazian",
    "ae": "Avestan",
    "af": "Afrikaans",
    "ak": "Akan",
    "am": "Amharic",
    "an": "Aragonese",
    "ar": "Arabic",
    "as": "Assamese",
    "av": "Avaric",
    "ay": "Aymara",
    "az": "Azerbaijani",
    "ba": "Bashkir",
    "be": "Belarusian",
    "bg": "Bulgarian",
    "bh": "Bihari languages",
    "bi": "Bislama",
    "bm": "Bambara",
    "bn": "Bengali",
    "bo": "Tibetan",
    "br": "Breton",
    "bs": "Bosnian",
    "ca": "Catalan; Valencian",
    "ce": "Chechen",
    "ch": "Chamorro",
    "co": "Corsican",
    "cr": "Cree",
    "cs": "Czech",
    "cu": "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic",
    "cv": "Chuvash",
    "cy": "Welsh",
    "da": "Danish",
    "de": "German",
    "dv": "Divehi; Dhivehi; Maldivian",
    "dz": "Dzongkha",
    "ee": "Ewe",
    "el": "Greek (Modern 1453-)",
    "en": "English",
    "eo": "Esperanto",
    "es": "Spanish",
    "et": "Estonian",
    "eu": "Basque",
    "fa": "Persian",
    "ff": "Fulah",
    "fi": "Finnish",
    "fj": "Fijian",
    "fo": "Faroese",
    "fr": "French",
    "fy": "Western Frisian",
    "ga": "Irish",
    "gd": "Gaelic; Scottish Gaelic",
    "gl": "Galician",
    "gn": "Guarani",
    "gu": "Gujarati",
    "gv": "Manx",
    "ha": "Hausa",
    "he": "Hebrew",
    "hi": "Hindi",
    "ho": "Hiri Motu",
    "hr": "Croatian",
    "ht": "Haitian; Haitian Creole",
    "hu": "Hungarian",
    "hy": "Armenian",
    "hz": "Herero",
    "ia": "Interlingua (International Auxiliary Language Association)",
    "id": "Indonesian",
    "ie": "Interlingue; Occidental",
    "ig": "Igbo",
    "ii": "Sichuan Yi; Nuosu",
    "ik": "Inupiaq",
    "io": "Ido",
    "is": "Icelandic",
    "it": "Italian",
    "iu": "Inuktitut",
    "ja": "Japanese",
    "jv": "Javanese",
    "ka": "Georgian",
    "kg": "Kongo",
    "ki": "Kikuyu; Gikuyu",
    "kj": "Kuanyama; Kwanyama",
    "kk": "Kazakh",
    "kl": "Kalaallisut; Greenlandic",
    "km": "Central Khmer",
    "kn": "Kannada",
    "ko": "Korean",
    "kr": "Kanuri",
    "ks": "Kashmiri",
    "ku": "Kurdish",
    "kv": "Komi",
    "kw": "Cornish",
    "ky": "Kirghiz; Kyrgyz",
    "la": "Latin",
    "lb": "Luxembourgish; Letzeburgesch",
    "lg": "Ganda",
    "li": "Limburgan; Limburger; Limburgish",
    "ln": "Lingala",
    "lo": "Lao",
    "lt": "Lithuanian",
    "lu": "Luba-Katanga",
    "lv": "Latvian",
    "mg": "Malagasy",
    "mh": "Marshallese",
    "mi": "Maori",
    "mk": "Macedonian",
    "ml": "Malayalam",
    "mn": "Mongolian",
    "mr": "Marathi",
    "ms": "Malay",
    "mt": "Maltese",
    "my": "Burmese",
    "na": "Nauru",
    "nb": "Bokmål (Norwegian); Norwegian Bokmål",
    "nd": "Ndebele (North); North Ndebele",
    "ne": "Nepali",
    "ng": "Ndonga",
    "nl": "Dutch; Flemish",
    "nn": "Norwegian Nynorsk; Nynorsk (Norwegian)",
    "no": "Norwegian",
    "nr": "Ndebele (South); South Ndebele",
    "nv": "Navajo; Navaho",
    "ny": "Chichewa; Chewa; Nyanja",
    "oc": "Occitan (post 1500); Provençal",
    "oj": "Ojibwa",
    "om": "Oromo",
    "or": "Oriya",
    "os": "Ossetian; Ossetic",
    "pa": "Panjabi; Punjabi",
    "pi": "Pali",
    "pl": "Polish",
    "ps": "Pushto; Pashto",
    "pt": "Portuguese",
    "qu": "Quechua",
    "rm": "Romansh",
    "rn": "Rundi",
    "ro": "Romanian; Moldavian; Moldovan",
    "ru": "Russian",
    "rw": "Kinyarwanda",
    "sa": "Sanskrit",
    "sc": "Sardinian",
    "sd": "Sindhi",
    "se": "Northern Sami",
    "sg": "Sango",
    "si": "Sinhala; Sinhalese",
    "sk": "Slovak",
    "sl": "Slovenian",
    "sm": "Samoan",
    "sn": "Shona",
    "so": "Somali",
    "sq": "Albanian",
    "sr": "Serbian",
    "ss": "Swati",
    "st": "Sotho (Southern)",
    "su": "Sundanese",
    "sv": "Swedish",
    "sw": "Swahili",
    "ta": "Tamil",
    "te": "Telugu",
    "tg": "Tajik",
    "th": "Thai",
    "ti": "Tigrinya",
    "tk": "Turkmen",
    "tl": "Tagalog",
    "tn": "Tswana",
    "to": "Tonga (Tonga Islands)",
    "tr": "Turkish",
    "ts": "Tsonga",
    "tt": "Tatar",
    "tw": "Twi",
    "ty": "Tahitian",
    "ug": "Uighur; Uyghur",
    "uk": "Ukrainian",
    "ur": "Urdu",
    "un": "Universal",
    "uz": "Uzbek",
    "ve": "Venda",
    "vi": "Vietnamese",
    "vo": "Volapük",
    "wa": "Walloon",
    "wo": "Wolof",
    "xh": "Xhosa",
    "yi": "Yiddish",
    "yo": "Yoruba",
    "za": "Zhuang; Chuang",
    "zh": "Chinese",
    "zu": "Zulu",
}


LANG_CODES = {
    'Afar': 'aa',
    'Abkhazian': 'ab',
    'Avestan': 'ae',
    'Afrikaans': 'af',
    'Akan': 'ak',
    'Amharic': 'am',
    'Aragonese': 'an',
    'Arabic': 'ar',
    'Assamese': 'as',
    'Avaric': 'av',
    'Aymara': 'ay',
    'Azerbaijani': 'az',
    'Bashkir': 'ba',
    'Belarusian': 'be',
    'Bulgarian': 'bg',
    'Bihari languages': 'bh',
    'Bislama': 'bi',
    'Bambara': 'bm',
    'Bengali': 'bn',
    'Tibetan': 'bo',
    'Breton': 'br',
    'Bosnian': 'bs',
    'Catalan; Valencian': 'ca',
    'Chechen': 'ce',
    'Chamorro': 'ch',
    'Corsican': 'co',
    'Cree': 'cr',
    'Czech': 'cs',
    'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic': 'cu',
    'Chuvash': 'cv',
    'Welsh': 'cy',
    'Danish': 'da',
    'German': 'de',
    'Divehi; Dhivehi; Maldivian': 'dv',
    'Dzongkha': 'dz',
    'Ewe': 'ee',
    'Greek (Modern 1453-)': 'el',
    'English': 'en',
    'Esperanto': 'eo',
    'Spanish': 'es',
    'Estonian': 'et',
    'Basque': 'eu',
    'Persian': 'fa',
    'Fulah': 'ff',
    'Finnish': 'fi',
    'Fijian': 'fj',
    'Faroese': 'fo',
    'French': 'fr',
    'Western Frisian': 'fy',
    'Irish': 'ga',
    'Gaelic; Scottish Gaelic': 'gd',
    'Galician': 'gl',
    'Guarani': 'gn',
    'Gujarati': 'gu',
    'Manx': 'gv',
    'Hausa': 'ha',
    'Hebrew': 'he',
    'Hindi': 'hi',
    'Hiri Motu': 'ho',
    'Croatian': 'hr',
    'Haitian; Haitian Creole': 'ht',
    'Hungarian': 'hu',
    'Armenian': 'hy',
    'Herero': 'hz',
    'Interlingua (International Auxiliary Language Association)': 'ia',
    'Indonesian': 'id',
    'Interlingue; Occidental': 'ie',
    'Igbo': 'ig',
    'Sichuan Yi; Nuosu': 'ii',
    'Inupiaq': 'ik',
    'Ido': 'io',
    'Icelandic': 'is',
    'Italian': 'it',
    'Inuktitut': 'iu',
    'Japanese': 'ja',
    'Javanese': 'jv',
    'Georgian': 'ka',
    'Kongo': 'kg',
    'Kikuyu; Gikuyu': 'ki',
    'Kuanyama; Kwanyama': 'kj',
    'Kazakh': 'kk',
    'Kalaallisut; Greenlandic': 'kl',
    'Central Khmer': 'km',
    'Kannada': 'kn',
    'Korean': 'ko',
    'Kanuri': 'kr',
    'Kashmiri': 'ks',
    'Kurdish': 'ku',
    'Komi': 'kv',
    'Cornish': 'kw',
    'Kirghiz; Kyrgyz': 'ky',
    'Latin': 'la',
    'Luxembourgish; Letzeburgesch': 'lb',
    'Ganda': 'lg',
    'Limburgan; Limburger; Limburgish': 'li',
    'Lingala': 'ln',
    'Lao': 'lo',
    'Lithuanian': 'lt',
    'Luba-Katanga': 'lu',
    'Latvian': 'lv',
    'Malagasy': 'mg',
    'Marshallese': 'mh',
    'Maori': 'mi',
    'Macedonian': 'mk',
    'Malayalam': 'ml',
    'Mongolian': 'mn',
    'Marathi': 'mr',
    'Malay': 'ms',
    'Maltese': 'mt',
    'Burmese': 'my',
    'Nauru': 'na',
    'Bokmål (Norwegian); Norwegian Bokmål': 'nb',
    'Ndebele (North); North Ndebele': 'nd',
    'Nepali': 'ne',
    'Ndonga': 'ng',
    'Dutch; Flemish': 'nl',
    'Norwegian Nynorsk; Nynorsk (Norwegian)': 'nn',
    'Norwegian': 'no',
    'Ndebele (South); South Ndebele': 'nr',
    'Navajo; Navaho': 'nv',
    'Chichewa; Chewa; Nyanja': 'ny',
    'Occitan (post 1500); Provençal': 'oc',
    'Ojibwa': 'oj',
    'Oromo': 'om',
    'Oriya': 'or',
    'Ossetian; Ossetic': 'os',
    'Panjabi; Punjabi': 'pa',
    'Pali': 'pi',
    'Polish': 'pl',
    'Pushto; Pashto': 'ps',
    'Portuguese': 'pt',
    'Quechua': 'qu',
    'Romansh': 'rm',
    'Rundi': 'rn',
    'Romanian; Moldavian; Moldovan': 'ro',
    'Russian': 'ru',
    'Kinyarwanda': 'rw',
    'Sanskrit': 'sa',
    'Sardinian': 'sc',
    'Sindhi': 'sd',
    'Northern Sami': 'se',
    'Sango': 'sg',
    'Sinhala; Sinhalese': 'si',
    'Slovak': 'sk',
    'Slovenian': 'sl',
    'Samoan': 'sm',
    'Shona': 'sn',
    'Somali': 'so',
    'Albanian': 'sq',
    'Serbian': 'sr',
    'Swati': 'ss',
    'Sotho (Southern)': 'st',
    'Sundanese': 'su',
    'Swedish': 'sv',
    'Swahili': 'sw',
    'Tamil': 'ta',
    'Telugu': 'te',
    'Tajik': 'tg',
    'Thai': 'th',
    'Tigrinya': 'ti',
    'Turkmen': 'tk',
    'Tagalog': 'tl',
    'Tswana': 'tn',
    'Tonga (Tonga Islands)': 'to',
    'Turkish': 'tr',
    'Tsonga': 'ts',
    'Tatar': 'tt',
    'Twi': 'tw',
    'Tahitian': 'ty',
    'Uighur; Uyghur': 'ug',
    'Ukrainian': 'uk',
    'Universal': 'un',
    'Urdu': 'ur',
    'Uzbek': 'uz',
    'Venda': 've',
    'Vietnamese': 'vi',
    'Volapük': 'vo',
    'Walloon': 'wa',
    'Wolof': 'wo',
    'Xhosa': 'xh',
    'Yiddish': 'yi',
    'Yoruba': 'yo',
    'Zhuang; Chuang': 'za',
    'Chinese': 'zh',
    'Zulu': 'zu'
}